### ISSUE TITLE
Video capture from Python-Mss

### ISSUE THREAD

**Issue by ljc19800331** [BoboTiG/python-mss#104]
General information:

* OS name: Linux_
* OS version: 16.04
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _800x600_
    * Monitor 2: _1920x1080_
* Python version: _3.6.4_
* MSS version: __3.2.0__

For GNU/Linux users:

* Display server protocol and version, if known: __X server__
* Desktop Environment: _XFCE 4_
* Composite Window Manager name and version: __Cairo v1.14.6__

### Description of the warning/error

Hello, I am wondering if we can capture the screenshot and at the same time record the video and output a .mp4 file with Mss. I checked multiple example end it seems difficult. Thanks.

**Comment by BoboTiG** [comment]
Hello,

I think you could save screenshots in a folder and use ffmpeg to convert PNGs to MP4?

**Comment by BoboTiG** [comment]
Did you try out?
