### ISSUE TITLE
XGetImage() failed while using mss with PyQt4 

### ISSUE THREAD

**Issue by allchanzi** [BoboTiG/python-mss#105]
General information:

* OS name: _Debian GNU/Linux_
* OS version: __sid__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _800x600_
    * Monitor 2: _1920x1080_
* Python version: _3.6.4_
* MSS version: __3.2.0__

For GNU/Linux users:

* Display server protocol and version, if known: __X server__
* Desktop Environment: _XFCE 4_
* Composite Window Manager name and version: __Cairo v1.14.6__

### Description of the warning/error

For testing i was using Tkinter library to get some UI and separately developing full UI in PyQt4 after i put them together i always get XGetImage() failed, i think PyQt4 somehow lock this function. So is there a way to use both these libraries in one project ?

**Comment by BoboTiG** [comment]
Hello,

Could you show some code I can investigate please.

**Comment by BoboTiG** [comment]
Also, could you use the latest version (4.0.1)? I fixed several memory leaks.

**Comment by BoboTiG** [comment]
Ping.
