### ISSUE TITLE
combined monitor image and mss().monitors incorrect

### ISSUE THREAD

**Issue by grintor** [BoboTiG/python-mss#108]
General information:

* OS name: Windows 10
* OS version: 10.0.17134.523
* OS architecture: x64
* Resolutions:
    * Monitor 1: 1600x900
    * Monitor 2: 1920x1080
* Python version: 3.7.0
* MSS version: 4.0.1

The combined monitor image is rendering incorrectly and (because?) the [monitors](https://python-mss.readthedocs.io/api.html#mss.tools.MSSBase) property returns invalid results.

If you look at my output from `print(sct.monitors)` you will see the results are impossible: 

`[{'left': 0, 'top': -172, 'width': 3520, 'height': 1252}, {'left': 0, 'top': 0, 'width': 1600, 'height': 900}, {'left': 1600, 'top': -172, 'width': 1920, 'height': 1080}]`

If I understand correctly, this output is saying that monitor 2 lies outside of the combination of all monitors together, which of course is impossible. I think this is what causes the 172-pixel black bar along the bottom of the image.

![fullscreen](https://user-images.githubusercontent.com/3444196/53049358-e0899e00-3464-11e9-8b67-ea82ece365f5.png)

I think the correct output of mss().monitors should be:

`[{'left': 0, 'top': 0, 'width': 3520, 'height': 1080}, {'left': 0, 'top': 172, 'width': 1600, 'height': 900}, {'left': 1600, 'top': 0, 'width': 1920, 'height': 1080}]`

here is a screenshot of my monitor position in windows display manager:

![image](https://user-images.githubusercontent.com/3444196/53050323-116ad280-3467-11e9-81fd-dc420e908487.png)

**Comment by grintor** [comment]
here is another broken screenshot:

![fullscreen](https://user-images.githubusercontent.com/3444196/53050762-1714e800-3468-11e9-9145-5354e47d6cfa.png)

I achieved this by shifting my monitor up in the windows display manager. like this:

![image](https://user-images.githubusercontent.com/3444196/53050867-4fb4c180-3468-11e9-8286-d223b817b21e.png)

In this case, the output of mss().monitors was correct:

`[{'left': 0, 'top': 0, 'width': 3520, 'height': 1080}, {'left': 0, 'top': 0, 'width': 1600, 'height': 900}, {'left': 1600, 'top': 0, 'width': 1920, 'height': 1080}]`

but monitor 1 was scaled up so that it's vertical resolution matched monitor 2 causing the left side of the screenshot to be cut off because it was now too big to fit on the canvas.

**Comment by BoboTiG** [comment]
Hello,

Thanks for the report!

I have no time now to investigate, but perhaps could you have a look? The revelant code is:

https://github.com/BoboTiG/python-mss/blob/497ec2de259db77d2289061f612902f29f1fe8dd/mss/windows.py#L206-L209

The fix may be easy?

**Comment by grintor** [comment]
Ok, well the all screen bounding rectangle problem was easy actually. It seemed to be a misunderstanding of what sm_cxvirtualscreen and  sm_cyvirtualscreen were. Here is the fix:

` 
            sm_xvirtualscreen, sm_yvirtualscreen = 76, 77
            sm_cxvirtualscreen, sm_cyvirtualscreen = 78, 79
            left = self.user32.GetSystemMetrics(sm_xvirtualscreen)
            width = self.user32.GetSystemMetrics(sm_cxvirtualscreen)
            top = self.user32.GetSystemMetrics(sm_yvirtualscreen)
            height = self.user32.GetSystemMetrics(sm_cyvirtualscreen)
			
            self._monitors.append(
                {
                    "left": int(left),
                    "top": int(top),
                    "width": int(width),
                    "height": int(height),
                }
            )
`

but the other problem, where the right screen overlaps the left screen seems to actually be a windows bug because the same thing happens with the native windows print-screen button is pressed. It's a little tricky to reproduce so I guess that's why microsoft didn't notice it. It happens when your primary monitor is a lower resolution than the secondary and  positioned on the left and above the secondary.

I think I can actually work around it by painting each monitor on a PIL canvas individually.

**Comment by grintor** [comment]
I was right. I was able to work around the windows bug like this:

import mss
from PIL import Image

```
sct = mss.mss()

all_mon = sct.monitors[0]
size = (all_mon['width'], (all_mon['height']))
img = Image.new('RGB', size)

for num, monitor in enumerate(sct.monitors[1:], 1):
	sct_img = sct.grab(monitor)

	monitor_img = Image.frombytes("RGB", sct_img.size, sct_img.bgra, "raw", "BGRX")
	
	position = (monitor['left'], monitor['top'])
	
	img.paste(monitor_img, position)

img.show()
```

**Comment by BoboTiG** [comment]
Oh, excellent! Do you mind opening a PR? (You could also add yourself to the CONTRIBUTORS file you want to).

As for the Windows bug, do you think it is something that can be fixed in MSS?

**Comment by BoboTiG** [comment]
Could you post a screenshot with the patched MSS to help understand the other issue please?

**Comment by BoboTiG** [comment]
@grintor a DPI bugfix has been merged in `master`, along with your patch about the screen boundering rectangle. Do you mind try this version?

**Comment by SergeyKalutsky** [comment]
![monitor-0](https://user-images.githubusercontent.com/34448296/54377246-d5a5e000-4695-11e9-8871-97b8272b79a8.png)
![examle2](https://user-images.githubusercontent.com/34448296/54377248-d5a5e000-4695-11e9-86dd-dbbca33294a4.png)
![examle3](https://user-images.githubusercontent.com/34448296/54377250-d5a5e000-4695-11e9-8a01-793f35ee8bf4.png)
![examle4](https://user-images.githubusercontent.com/34448296/54377252-d63e7680-4695-11e9-9d30-cb504e045343.png)

I've made some tests. It looks like if monitors go in corretc order, e.g 1-left, 2-right or 1-top, 2-bottom screenshots are correct. But when they go in reverse 2-left, 1-right, it counts 2 monitor twise, because it starts at negative values:
`[{'left': -1366, 'top': 0, 'width': 4652, 'height': 1080}, {'left': 0, 'top': 0, 'width': 1920, 'height': 1080}, {'left': -1366, 'top': 0, 'width': 1366, 'height': 768}]`

**Comment by SergeyKalutsky** [comment]
monito #1
![monitor1 4](https://user-images.githubusercontent.com/34448296/54377985-629d6900-4697-11e9-8a13-a3b0b953b8ac.png)
![monitor1](https://user-images.githubusercontent.com/34448296/54378040-7943c000-4697-11e9-839c-18d8b957e4ac.png)
![monitor1 2](https://user-images.githubusercontent.com/34448296/54378042-7943c000-4697-11e9-8bbc-b32039564020.png)


![monitor1 3](https://user-images.githubusercontent.com/34448296/54377986-629d6900-4697-11e9-8e04-fdd7920f8e02.png)

**Comment by SergeyKalutsky** [comment]
Monitor 2
![monitor2 4](https://user-images.githubusercontent.com/34448296/54378392-464dfc00-4698-11e9-80bd-97d6a8e0ac76.png)
![monitor2 1](https://user-images.githubusercontent.com/34448296/54378393-464dfc00-4698-11e9-93e3-b502d2e3ec77.png)
![monitor2 2](https://user-images.githubusercontent.com/34448296/54378394-464dfc00-4698-11e9-966b-410025ae124c.png)
![monitor2 3](https://user-images.githubusercontent.com/34448296/54378395-464dfc00-4698-11e9-8114-10d95b76f653.png)

**Comment by SergeyKalutsky** [comment]
If I'll have some time I will work on a fix. Shouldn't be hard to do.

**Comment by SergeyKalutsky** [comment]
My bad, didn't pull the last commit. Everything works just fine.
![ex2](https://user-images.githubusercontent.com/34448296/54419637-08dd8300-4719-11e9-91ae-b0a1667ff556.png)
![ex3](https://user-images.githubusercontent.com/34448296/54419638-09761980-4719-11e9-8aca-b8a387efe7a4.png)
![ex1](https://user-images.githubusercontent.com/34448296/54419639-09761980-4719-11e9-975d-752b2c056c47.png)
![ex4](https://user-images.githubusercontent.com/34448296/54419641-09761980-4719-11e9-9e89-25b306fd329d.png)

**Comment by BoboTiG** [comment]
Ah this is a very good new! Thanks for testing @SergeyKalutsky, and thanks for the second patch @grintor :)
