### ISSUE TITLE
SigSegv when using mss on latest ubuntu

### ISSUE THREAD

**Issue by cycomanic** [BoboTiG/python-mss#11]
General informations:
- OS name: Ubuntu
- OS version: 16.10
- OS architecture: _64 bits_
- Result of the command `python --version`: Python 2.7.12+ and Python 3.5.2+

For GNU/Linux users:
- Display server protocol and version, if known: X.Org X Server 1.18.4
- Desktop Environment: N/A
- Composite Window Manager name and version: qtile 10.6
### Description of the warning/error

trying to use MSS results in a SIGSEGV when calling enum_display_monitors() 
If I run the first lines of the example given in the README

```
>>> from mss import mss
>>> sct = mss(display=b':0')

# Retrieve monitors informations
>>> displays = sct.enum_display_monitors()
```

the program terminates with:
fish: “python” terminated by signal SIGSEGV (Address boundary error)

I've already tried recompiling the C library on my machine but no difference

**Comment by BoboTiG** [comment]
Hi @cycomanic,

First, what is the result of:

    echo $DISPLAY

Then, can you try with the latest updates from the `dev` branch?

    git clone https://github.com/BoboTiG/python-mss.git
    cd python-mss
    git checkout dev

And try, in a Python console:

    >>> from mss import mss
    >>> sct = mss()
    >>> displays = sct.enum_display_monitors()

**Comment by cycomanic** [comment]
HI @BoboTiG 

DISPLAY is :0 

I tried the latest dev branch, same issue (also tried running from script, or python console. I've done a bit of digging and this seems to happen whenever a one of the non-pointer fields of XRRScreenResources is accessed.

**Comment by BoboTiG** [comment]
Which exact ISO did you do download for Ubuntu? I will try tomorrow to reproduce the error.
In any case, thanks for the report :)

**Comment by cycomanic** [comment]
This is the latest 16.10 beta (forgot the codename). I figured out what's causing this, although it's been a long time since I used ctypes so I'm not sure I understand. The issue seems to be the validate return type for `XRRGetScreenResources`.
If I change
```python
 self.xrandr.XRRGetScreenResources.restype = validate
```
to 
```python
 self.xrandr.XRRGetScreenResources.restype = POINTER(XRRScreenResources) 
``` 
everything works. So it seems ctypes is not happy that you set the return type to your Null pointer check.

**Comment by cycomanic** [comment]
OK I just had a look at the latest ctypes documentation:

> restype
>
>    Assign a ctypes type to specify the result type of the foreign function. Use None for void, a function not returning anything.
>
>    It is possible to assign a callable Python object that is not a ctypes type, in this case the function is assumed to return a C int, and the callable will be called with this integer, allowing further processing or error checking. Using this is deprecated, for more flexible post processing or error checking use a ctypes data type as restype and assign a callable to the errcheck attribute.

So it seems in my ctypes the callable method is not working anymore.

**Comment by alxchk** [comment]
What about to update mss in pip? Dev branch works for me, while pip versions fails to SIGSEGV

**Comment by BoboTiG** [comment]
I will update just now, thanks for the reminder :)
