### ISSUE TITLE
Screen Capture Wrong Size - OSX

### ISSUE THREAD

**Issue by FirefoxIstSchon** [BoboTiG/python-mss#121]
General information:

* OS name: OS X
* OS version: High Sierra
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: width = 200 , height = 200
    * Monitor 2: -
* Python version: 3.6
* MSS version: 4.0.2

### Description of the warning/error

1) the given monitor["height"] & monitor["width"] gets multiplied by 2
i.e. 200x200 => 400x400

2) the resulting array is larger than height x width x channels

### Full message

    box = {'top': 0, 'left': 0, 'width': 200, 'height': 200}

    screen = sc.grab(box)
    print(screen.width, screen.height) => 400 400 
      - shouldn't this be 200 x 200 ?

    np_arr = numpy.array(screen)
    print(np_arr.size) => 640000 
      - shouldn't this be 400^2 x 3 ? (assuming 400 was the correct w/h)

**Comment by BoboTiG** [comment]
Hello @FirefoxIstSchon,

This is the normal behavior on High Sierra or any macOS version with its Retina display. This is the cost of HiDPI :)
There are [few ways](https://apple.stackexchange.com/questions/105185/how-can-i-stop-my-retina-display-from-taking-2x-sized-screenshots) to reduce the size, but nothing implemented in MSS.

I do not think it is an issue, do you?
