### ISSUE TITLE
Mss detecting a huge ghost screen

### ISSUE THREAD

**Issue by LoudMurmur** [BoboTiG/python-mss#124]
General information:

* OS name:  Windows 10
* OS version: version 1803 (17134.648)
* OS architecture: 64 bits
* Resolutions:
    * Monitor 1: 1680x1050 Acer B223W (right, windows main monitor)
    * Monitor 2: 1680x1050 Acer B223WL (center)
    * Monitor 3: 1680x1050 Acer B223W (left)
* Python version: 2.7.15
* MSS version: 4.0.2

### Description of the warning/error

A huge ghost monitor seem to be detected by mss.

### Full message

When I do

>>> for mon in mss.mss().monitors:
...     print mon

I get 

    {'width': 8400, 'top': 0, 'height': 1050, 'left': -3360} <- that is not one of mine
    {'width': 1680, 'top': 0, 'height': 1050, 'left': 0}
    {'width': 1680, 'top': 0, 'height': 1050, 'left': -1680}
    {'width': 1680, 'top': 0, 'height': 1050, 'left': -3360}

After trying 

>>> filename = mss.mss().shot(mon=-1, output=r'c:\checkouts\fullscreen.png')
>>> filename = mss.mss().shot(mon=1, output=r'c:\checkouts\fullscreen1.png')
>>> filename = mss.mss().shot(mon=2, output=r'c:\checkouts\fullscreen2.png')
>>> filename = mss.mss().shot(mon=3, output=r'c:\checkouts\fullscreen3.png')
>>> filename = mss.mss().shot(mon=0, output=r'c:\checkouts\fullscreen0.png')

mon=0 and mon = 1 : both contain the same picture, monitor 1 in windows (right, main)
mon=2 : monitor 2 in windows (center)
mon=3 : monitor 3 in windows (left)

mon=-1 contains my 3 monitors side by side with a black "monitor" which has a 8400 pixels width like this : [mon3] [mon2] [mon1] [---- ghost monitor -----]

### Other details
I'm using 2 'foxconn' displayport -> DVI adapter for my additionals monitor on a quadro K2000 with drivers version 335.78.
One of the monitors uses the DVI socket of the GPU.

The foxconn adapter have this written on them :
BN39-00246S
GM1250

Here you can see the ghost monitor on the right

![fullscreen](https://user-images.githubusercontent.com/1658755/56579626-f6d0e900-65d0-11e9-840d-220041963056.png)

Thanks.

**Comment by BoboTiG** [comment]
The screenshot tool from Windows returns what picture?

**Comment by LoudMurmur** [comment]
The printScreen key of my keyboard returns the 3 screens without the ghost monitor.

Unfortunatly, we have to maintain something that is in 2.7.

**Comment by BoboTiG** [comment]
OK then could you try the version from the `python2-with-backported-monitor-fixes` branch?

**Comment by LoudMurmur** [comment]
this indeeds correct the issue

    pip uninstall mss

    C:\checkouts\python-mss>python setup.py install


>>> for mon in mss.mss().monitors:
...     print mon

    {'width': 5040, 'top': 0, 'height': 1050, 'left': -3360}
    {'width': 1680, 'top': 0, 'height': 1050, 'left': 0}
    {'width': 1680, 'top': 0, 'height': 1050, 'left': -1680}
    {'width': 1680, 'top': 0, 'height': 1050, 'left': -3360}


>>>mss.mss().shot(mon=-1, output=r'c:\checkouts\fullscreen_python2-with-backported-monitor-fixes.png')

    'c:\\checkouts\\fullscreen_python2-with-backported-monitor-fixes.png'
![fullscreen_python2-with-backported-monitor-fixes](https://user-images.githubusercontent.com/1658755/56584046-3270b080-65db-11e9-9bc7-8d3a536e22f9.png)

**Comment by BoboTiG** [comment]
Great! I will publish MSS 4.0.3 version just now :)

**Comment by BoboTiG** [comment]
(for history) This issue is a duplicate of #108 and #116 together.

**Comment by BoboTiG** [comment]
MSS 4.0.3 is no online!
