### ISSUE TITLE
How can I make it continuous automatic screenshots?

### ISSUE THREAD

**Issue by kerbalwzy** [BoboTiG/python-mss#125]
I use MMS in subthreads of GUI programs.

But I found that if I did not move the mouse actively, It would not take a screenshot, which seemed to cause a blockage.

How can I make it continuous automatic screenshots?

Codes are here:
https://github.com/kerbalwzy/ScreenMonitor/blob/master/client/videoFrame.py

**Comment by kerbalwzy** [comment]
I find it's not a problem with MSS package, Sorry.

**Comment by BoboTiG** [comment]
No worry :)
