### ISSUE TITLE
gdi32.GetDIBits() failed when two .grab() areas overlap

### ISSUE THREAD

**Issue by shrddr** [BoboTiG/python-mss#128]
General information:

* OS name: Windows
* OS version: 10
* OS architecture: 64 bits
* Resolutions:
    * Monitor 1: 1920x1080
* Python version: 3.6.5
* MSS version: 4.0.3

### Description of the warning/error

Calling .grab in a loop twice with specific area configurations leads to gdi32.GetDIBits() failed after 4996..4998 loops

```
# ok
#area1 = {"top": 100, "left": 100, "width": 400, "height": 320, "mon": 1 }
#area2 = {"top": 200, "left": 200, "width": 320, "height": 320, "mon": 1 }  

# ok
#area1 = {"top": 50, "left": 7, "width": 300, "height": 300, "mon": 1 }
#area2 = {"top": 200, "left": 200, "width": 300, "height": 300, "mon": 1 }

# fail
area1 = {"top": 50, "left": 7, "width": 400, "height": 320, "mon": 1 }
area2 = {"top": 200, "left": 200, "width": 320, "height": 320, "mon": 1 }

i = 0
with mss.mss() as sct:
    while "Screen capturing":
        try:
            frame1 = sct.grab(area1)
            frame2 = sct.grab(area2)
            i += 1
        except mss.ScreenShotError as e:
            print("fail at:", i)
            raise e
```

After one fail, rerunning the same script produces same error immediately. Have to restart Python to make it work for 4996 more loops.

### Full message

fail at: 4996
ScreenShotError: gdi32.GetDIBits() failed.

### Other details

Same behaviour at machine with Windows 7, Python 3.7.0 and different monitor configuration

**Comment by BoboTiG** [comment]
Could you try to use the version from the master branch?

**Comment by BoboTiG** [comment]
It is fixed on master. I will release a new version in the week. Thanks for the report :)
