### ISSUE TITLE
Memory increase slowly and then fill up all memory

### ISSUE THREAD

**Issue by Seraphli** [BoboTiG/python-mss#137]
General information:

* OS name: Windows
* OS version: 7
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _1920x1080_
    * Monitor 2: _1920x1080_
* Python version: _3.7.5_
* MSS version: __4.0.3__

### Description of the warning/error

I'm running a script to capture screen in VMware. The system win7 is running inside VMware.
I dispatch 6GB memory for this machine. After running the script for about 6 hours, the python process fills up all memory and cause the Out of Memory error.

**Comment by BoboTiG** [comment]
Could you try the version from the master branch? Several memory leak issues were fixed.

**Comment by Seraphli** [comment]
Okay, I will try it out. I'm currently just writing a bat script to restart the python script.

**Comment by Seraphli** [comment]
I have tested the version 5.0.0 for 15 minutes, and the problem is resolved. Thank you!
I will run a test for hours later, see if there is a problem.
I will close this issue now.

**Comment by BoboTiG** [comment]
Great! I will make a new release this week. Let me know if you problem is really solved (I think so).

**Comment by Seraphli** [comment]
Confirm the problem solved.

**Comment by BoboTiG** [comment]
Excellent! Thank you :)
