### ISSUE TITLE
Bad multiple screen grab

### ISSUE THREAD

**Issue by Archarachne** [BoboTiG/python-mss#14]
I'm working on 10.12.1 MacOS Sierra with 2.0.18 mss version and python 3.5. When today I tried to create multiple screenshots using mss according to documentation.
And with two different screens with resolutions 
{'height': 1200, 'left': 0, 'top': 0, 'width': 1920}, {'height': 768, 'left': -1366, 'top': 0, 'width': 1366}. The bigger screenshot looks fine but the smaller gives a very bad result: http://imgur.com/a/hKrHw. What is the cause of it?

**Comment by BoboTiG** [comment]
Woops, weird. Few questions to try to understand, following [examples](https://python-mss.readthedocs.io/en/latest/examples.html#examples):
1. If you take the screenshot of all monitors, what is the result?
2. What is the result if you take one screenshot per monitor?
3. What is the result if you specify which monitor to capture?

**Comment by Archarachne** [comment]
So following the examples:

1. If both monitors are get a screenshot together the picture looks like the one attached only mixed together.
2. 3 - the screenshot of the bigger, primary screen is always perfect; the other-smaller gets mixed.

**Comment by BoboTiG** [comment]
If you set the little screen as primary one, same results? How is connected the second screen (nothing special on the set-up part, or something helpful?) ?

**Comment by Archarachne** [comment]
It's connected via HDMI and thunderbolt adapter. I'm checking the primary screen right now.

**Comment by Archarachne** [comment]
After switching primary setting between the screens the small one (I own 11 inch MacBook Air with 10.12.1 Sierra) always gives a bad picture while the big one is ok (with bigger resolution).

**Comment by BoboTiG** [comment]
OK, you are using a Thunderbold adaptater, good to know. I will have testing hardware in january, but for now I cannot try something for you :/

**Comment by Archarachne** [comment]
Thanks, will be waiting for an update. 👍 

The funny thing is that the MacBook air screen has got a problem, not the attached monitor. I would expect otherwise. :)

**Comment by BoboTiG** [comment]
Hello,

Finally, I could get a machine and a Thunderbolt adaptater. But all screenshots are good :/
Do you have a clue, something special in your configuration that could interfer? The monitor state i "normal"?

**Comment by vvarp** [comment]
Got hit by the same issue running on MacBook Air 11" - a machine with fairly uncommon native resolution (1366x768)

Resulting PNG is at correct resolution, however at closer inspection it looks like there's 10 black pixels inserted at the end of each scanline - clearly that's since 1366 is not divisible by 16 (and 1376 is).

I know close to nothing about CoreGraphics internals, so I am really unable to debug it further - any clues would be appreciated!

**Comment by BoboTiG** [comment]
Hello,

That is a good clue, thanks. I will investigate soon.

**Comment by DavideBecker** [comment]
I've encountered a similar issue. Most likely related. Using a MacBook Air 13" with a resolution of 1440x900 and no 2nd screen. Using 
`sct.get_pixels({'left': 0, 'top': 0, 'width': 1440, 'height': 900})`
works just fine, but when I change it to 
`sct.get_pixels({'left': 0, 'top': 0, 'width': 1400, 'height': 900})`
(Changing the width) I get a very distorted image 

![http://i.imgur.com/wh85Cbl.png](http://i.imgur.com/wh85Cbl.png)

So after some more experimentation it looks like some sort of rounding issue. `sct.get_pixels({'left': 0, 'top': 0, 'width': 720, 'height': 900})`
(Half the width of the full resolution) Also looks totally normal.

Kudos though, it's still a pretty awesome package

**Comment by BoboTiG** [comment]
@Archarachne, @vvarp and @DavideBecker: Could you try the [PIL example](https://python-mss.readthedocs.io/en/dev/examples.html#using-pil)? It will help locate the issue.

**Comment by DavideBecker** [comment]
Works fine for me, but if I change `sct.get_pixels(monitor)` to `        sct.get_pixels({
            "top": 200,
            "left": 200,
            "width": 200,
            "height": 200
        })` in order to only get part of the screen, the image gets distorted again. 

![http://i.imgur.com/T58VPKG.png](http://i.imgur.com/T58VPKG.png)

However, it looks like if the **width is a multiple of 16** (e.g. `sct.get_pixels(monitor)` to `        sct.get_pixels({
            "top": 160,
            "left": 160,
            "width": 160,
            "height": 160
        })`) everything works like it should.

![http://i.imgur.com/hFzWEni.png](http://i.imgur.com/hFzWEni.png)

**Comment by BoboTiG** [comment]
OK, I added an [example to capture a part of the screen](https://python-mss.readthedocs.io/en/dev/examples.html#part-of-the-screen). It works well on GNU/Linux, whatever the `width`.
Can I ask you to try out this code?

**Comment by DavideBecker** [comment]
Running exactly that code gives me this image:

![http://i.imgur.com/Omvl3QD.png](http://i.imgur.com/Omvl3QD.png)

It looks like this is some odd OSX bug. Really seems like some pixels move to a row where they shouldn't. Either too many or too few.

**Comment by BoboTiG** [comment]
Can you print the detected dimensions to check they are not changed by the OS:

    from mss import mss

    with mss() as sct:
        mon = {'top': 160, 'left': 160, 'width': 222, 'height': 42}

        # Create the picture
        output = 'sct-{top}x{left}_{width}x{height}.png'.format(**mon)
        sct.to_png(sct.get_pixels(mon), output)
        print(output)

        print('{}x{}'.format(sct.width, sct.height))

**Comment by DavideBecker** [comment]
That gives me the expected `222x42`

**Comment by BoboTiG** [comment]
Hm, it is a good thing. I will be able to try on a Mac soon. I have in mind an mistake with the *bits per pixel* value, but I cannot say anything right now.

**Comment by DavideBecker** [comment]
I've been playing with various print statements and a buddy of mine stumbled upon [this](http://stackoverflow.com/questions/16171283/mac-os-x-quartz-cgwindowlistcreateimage-scrambles-image-on-1366x768-resolutions#17389894) Stackoverflow answer which looks very promising.

**Comment by BoboTiG** [comment]
I have time to work on it now. Could you save the content of `sct.image` to a file and share it with me?

**Comment by DavideBecker** [comment]
We've been tinkering a bit and I think we're pretty close to a good solution. I'll polish up the code and submit a pull request.

**Comment by BoboTiG** [comment]
The fix has been pushed to the dev branch. I will wait for your responses before merging to master and uploading to PyPi. Thanks @DavideBecker for the fix :)
