### ISSUE TITLE
[Windows] Black screen when used from Task scheduler (+fix)

### ISSUE THREAD

**Issue by graz68a** [BoboTiG/python-mss#149]
General information:

* OS name: Windows10
* OS architecture: 64 bits
* Resolutions: 2k monitor Blenq
* Python version: 3.7.32
* MSS version: 5.0.0.

### Description of the warning/error

I'm using this Python code to generate a Windows 10 desktop screenshot every 10 seconds 
and save it in d:/screen/work/ folder. It works very well and extremely fast .
I execute the code from Windows command prompt (cmd.exe) 

# python d:/screeen/screen.py

```

import mss
import mss.tools
import datetime
import time

count = 0
while count < 100000000:
    with mss.mss() as sct:
        monitor = sct.monitors[1]
        timestr = time.strftime("%Y%m%d-%H%M%S")
        sct.compression_level = -1
        output = "d:/screen/work/" + (timestr) + ".png".format(**monitor)
        sct_img = sct.grab(monitor)
        mss.tools.to_png(sct_img.rgb, sct_img.size, output=output)
        print(output)    

    time.sleep(10)
    count += 1
```

The problem starts when I try to automatize the script. I want the script starts automatically when I turn on the computer and I loggin in and I do not want the command window appears.
I followed this guide  https://www.howtogeek.com/tips/how-to-run-a-scheduled-task-without-a-command-window-appearing/

When I login in computer the Pyhton script starts correctly , no command window appears, 
but in my d:/screen/work/ folder are saved only full black screenshots !

How to avoid this ?

Thank you

**Comment by graz68a** [comment]
I found now that someone reported the same here
https://github.com/BoboTiG/python-mss/issues/67#issuecomment-428738149
"I have similar issue when running a script that takes a full screen screenshot; running the code on console works but running the script from a windows service app only returns a black screen"

Does exist any solution to this ?

**Comment by BoboTiG** [comment]
Hello,

If you use the "Run only when user is logged on" option in the task, does it work?

**Comment by graz68a** [comment]
no it does not work too. However I found the solution , and the solution is executing it using python**w** instead of python .

**Comment by BoboTiG** [comment]
Ah, great news, thanks :)

And if I may, you could rewrite your code to something like that:
```python
import mss
import time

count = 0
with mss.mss() as sct:
    sct.compression_level = -1

    while "screenshotting":
        file_path = sct.shot(output="d:/screen/work/{date:%Y%m%d-%H%M%S}.png")
        count += 1

        print(file_path)
        time.sleep(10)
```

**Comment by ubalklen** [comment]
I have the same problem. `pythonw.exe` didn't solve it.

My code is very simple:

```
# myscript.py
from mss import mss
from time import localtime, strftime
from random import random

PROB = 0.99

if random() <= PROB:
    with mss() as sct:
        filename = strftime("%d%m%Y_%H%M%S", localtime()) + ".png"
        sct.shot(mon=-1, output=filename)
```

I'm using the "Start a program action" in the task scheduler, with the following parameters:
- Program/script: `E:\Users\user\miniconda3\envs\myenv\pythonw.exe`
- Arguments: `E:\Users\user\Documents\Code\myscript\myscript.py`
- Start in: `E:\Users\user\Desktop`

It doesn't work even when I'm logged on or if I trigger the task manually.

Interestingly, I can open a PowerShell from the desktop, run the exact command in the task (`E:\Users\user\miniconda3\envs\myenv\pythonw.exe E:\Users\user\Documents\Code\myscript\myscript.py`) and it works like a charm, so I'm guessing it's something specific to the scheduler.

@BoboTiG please let me know if you rather have a new issue for this.
