### ISSUE TITLE
High FPS Greyscale Screenshots

### ISSUE THREAD

**Issue by jmdots** [BoboTiG/python-mss#16]
Hi.

I'm interested in capturing greyscale screenshots at a very high rate for use in machine learning tasks (see [1] for an example).  I've found mss to be fast at capturing color and greyscale screenshots compared to other solutions. Nevertheless, on MacOS, to use `cv2` with them via PIL, I think the BGR<->RGB happens twice (once in mss and another time in PIL) before I send it off to greyscale.

This made me think to ask you if an option to go straight to greyscale would make sense for mss.  I saw an old issue closed stating that greyscale wasn't in line with project goals.  I suspect that would be because someone can convert easily to greyscale down the line.  However, if the conversion happens upstream at mss, the data flowing downstream is 1/3 the size I believe.  Perhaps there would be an frames per second (performance) boost if greyscale could be captured early/directly?

Thanks for this great project.

Please let me know your thoughts. (I'm new to graphical processing in python3.)

Thanks,
Joshua

[1] https://www.youtube.com/watch?v=edWI4ZnWUGg

**Comment by BoboTiG** [comment]
Hello Joshua,

It is certainly something I can consider. IT is you on the video and blog post? I am curious to see your code :)

How would you see that implemented? Using a callback function as attribute?
Also, I can add a boolean attribute `raw` (or something like that) to the base class to tell MSS we do not want the BGRA -> RGB conversion, just returns raw data.

**Comment by BoboTiG** [comment]
In the `dev` branch, I added [examples](https://github.com/BoboTiG/python-mss/tree/dev/examples).
You can have a look at the up-to-date [API documentation](https://python-mss.readthedocs.io/en/dev/api.html).
Please let me know if it is good for you, I added OpenCV and Numpy integrations. Computing is insanely fast now (see examples and the [FPS test](https://github.com/BoboTiG/python-mss/blob/dev/tests/fps.py)).
