### ISSUE TITLE
Grabbing screen concurrently crashes with Linux.

### ISSUE THREAD

**Issue by mihaiparvu** [BoboTiG/python-mss#169]
General information:

* OS name: _Debian GNU/Linux_ (VirtualBox)
* OS version: _10_
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _800x600_
* Python version: _3.7.3_
* MSS version: _5.1.0_

For GNU/Linux users:

* Display server protocol and version, if known: __X server__
* Desktop Environment: _XFCE 4_
* Composite Window Manager name and version: __Cairo v1.14.6__

### Description of the warning/error

Grabbing screen concurrently by using threads crashes mss when running with Linux.

Code to reproduce:

```python
import time
import threading

from mss import mss


# record for one second
def record():
    start_time = time.time()
    while time.time() - start_time < 1:
        with mss() as sct:
            sct.grab(sct.monitors[1])


t1 = threading.Thread(target=record)
t2 = threading.Thread(target=record)

t1.start()
time.sleep(0.5)
t2.start()
```

### Full message

```
[xcb] Unknown sequence number while processing reply
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
python3: ../../src/xcb_io.c:643: _XReply: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted
```
### Other details

This is working fine under Windows (5.1.0) and when running with Linux and using and older mss version (4.0.3).

**Comment by BoboTiG** [comment]
Hey,

Sorry for the long delay. Thank you for the report, it will be fixed ASAP :)

**Comment by mihaiparvu** [comment]
No worries. Thanks for the fix and your great work!
