### ISSUE TITLE
Make the package available on conda-forge?

### ISSUE THREAD

**Issue by giswqs** [BoboTiG/python-mss#170]
It would be great if the python-mss package can be made available on [conda-forge](https://conda-forge.org/). There is another package named [mss](https://anaconda.org/conda-forge/mss)  (Mission Support System) on conda-forge, which causes confusion with this python-mss.

**Comment by BoboTiG** [comment]
Hello,

It could be made available on conda, of course. I just need to read the documenation, this is all new for me :)

I will give a try ASAP.

**Comment by giswqs** [comment]
Yes, I think the package name `python-mss` should be fine. I have creatred the [meta.yaml](https://gist.github.com/giswqs/f3a1c9edf14ab9cf2fc4dcc428cda9e5) for you. This was created using `conda skeleton pypi mss` with some additional edits. You just need to fork [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes) and add a python-mss folder with the meta.yaml and LICENSE to the [recipes](https://github.com/conda-forge/staged-recipes/tree/master/recipes) folder. Submit a pull request and wait for the review and approval. 

You can see my previous [pull request](https://github.com/conda-forge/staged-recipes/pull/11094) as an example.

**Comment by BoboTiG** [comment]
Super, thanks for your help :)

:arrow_right: https://github.com/conda-forge/staged-recipes/pull/12030

**Comment by BoboTiG** [comment]
This is now reality: https://anaconda.org/conda-forge/python-mss :champagne: 
```shell
conda install -c conda-forge python-mss
```

**Comment by giswqs** [comment]
Fantastic! Thank you very much.
