### ISSUE TITLE
Support request: macOS Big Sur

### ISSUE THREAD

**Issue by jack-ditto** [BoboTiG/python-mss#178]
General information:

* OS name: OS X Big Sur
* OS version: 11.0 Beta
* OS architecture: _64 bits_
* Python version: _3.7.2_
* MSS version: __3.2.0__

### Description of the warning/error

When trying to use MSS, such as I am in the following code 

```
mon = {'top': 160, 'left': 160, 'width': 200, 'height': 200}

sct = mss()

while 1:
    sct.get_pixels(mon)
    img = Image.frombytes('RGB', (sct.width, sct.height), sct.image)
    cv2.imshow('test', np.array(img))
    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break

```
You get an error: mss.exception.ScreenShotError: No CoreGraphics library found. This is because in Big Sur, dynamic libraries that are included in the OS are no longer present in the file system and can only be found by trying to open them with dlopen(). As an example:

```
>>> p = "/System/Library/Frameworks/CoreFoundation.framework/Versions/Current/CoreFoundation"
>>> os.path.exists(p)
False
>>> cffi.FFI().dlopen(p)
<cffi.api.FFILibrary_/System/Library/Frameworks/CoreFoundation.framework/Versions/Current/CoreFoundation object at 0x10f02b590>

```
### Full message

```
    Traceback (most recent call last):
  File "main-mss.py", line 8, in <module>
    sct = mss()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mss/factory.py", line 36, in mss
    return darwin.MSS(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mss/darwin.py", line 77, in __init__
    raise ScreenShotError("No CoreGraphics library found.")
mss.exception.ScreenShotError: No CoreGraphics library found.

```

**Comment by BoboTiG** [comment]
Hello,

Thanks for the report.
Unfortunately, I do not have a machine with Big Sur for now. I would also wait and see for https://bugs.python.org/issue41100, maybe will this be handled at the source.

But in any cases, there will still need a patch for Python versions < 3.8 ...

Do you mind proposing a PR? If you can't, no worry, I will have a look when I could.

**Comment by cjkumar** [comment]
I also have this exact same issue since upgrading to big sur

**Comment by BoboTiG** [comment]
It works, just update MSS to the latest version.

**Comment by cjkumar** [comment]
"pip install --upgrade mss" Solved it for me
Thank you @BoboTiG
