### ISSUE TITLE
Fixing Mouse Flicker when doing rapid Screenshots

### ISSUE THREAD

**Issue by BanditTech** [BoboTiG/python-mss#179]
General information:

* OS name: Windows
* OS version: 10
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _1920x1080_
    * Monitor 2: _1920x1080_
* Python version: _3.8.3_
* MSS version: __6.0.0__

### Description of the warning/error

This issue occurs when taking rapid screenshots of a fullscreen game. I have an issue of the mouse flickering on the screen, constantly disappearing and reappearing.

### Full message

There is no error, it functions as intended and the output is the proper screen capture.

### Other details

In order to resolve this issue I have manually adjusted the parameters of the capture within the windows.py file.

Excluding the value CAPTUREBLT ( 0x40000000 ) fixes the issue and allows the captures to happen rapidly without affecting the cursor.

The line is on 290
remove the " | CAPTUREBLT " and it resolves the issue.

**Comment by BoboTiG** [comment]
What you could do is simething like:
```python
import mss.windows
mss.windows.CAPTUREBLT = 0

# And then you do the screenshot
import mss
# ...
```
(not tested)

**Comment by BanditTech** [comment]
Thank you, this fixes it in a much more elegant way than ablation. 👍

**Comment by Boxylmer** [comment]
Fastest issue I've ever found an immediate solution to. Thanks!
