### ISSUE TITLE
How to capture the screen with a specific fps?

### ISSUE THREAD

**Issue by hcao720** [BoboTiG/python-mss#181]
Is there any way to capture the screen with a specific fps by applying mss?

**Comment by sagarreddypatil** [comment]
This better belongs on StackOverflow, but I'll answer the question anyways.

In order to run a python loop at a certain FPS, you can delay based on the time taken for a process.

```
import time
MAX_FPS=60
MIN_FRAME_TIME=1/MAX_FPS

while True:
  start = time.time()
  # screen capture
  time.sleep(max(0, MIN_FRAME_TIME - (time.time() - start)))
```

Hope this helps :)

**Comment by hcao720** [comment]
Thanks!!!☺️

在 2020年10月22日，10:41，Sagar Patil <notifications@github.com> 写道：

﻿

This better belongs on StackOverflow, but I'll answer the question anyways.

In order to run a python loop at a certain FPS, you can delay based on the time taken for a process.

import time
MAX_FPS=60
MIN_FRAME_TIME=1/MAX_FPS

while True:
  start = time.time()
  # screen capture
  time.sleep(max(0, MIN_FRAME_TIME - (time.time() - start)))


Hope this helps :)
