### ISSUE TITLE
OpenCV/Numpy example not working correctly on macOS

### ISSUE THREAD

**Issue by aryarohit07** [BoboTiG/python-mss#19]
Hi,
First of all, thank for a great library.
I encountered some issues while trying to record my screen.

General informations:

* MSS version: 3.0.1
* OS name: macOS Sierra
* OS version: 10.12.5 (16F73)
* OS architecture: 64 bits
* Result of the command `python --version`: Python 3.5.3
* OpenCV version: opencv3 : 3.1.0
* Numpy Version: 1.12.1

### Description of the warning/error
I tried out [OpenCV/Numpy example](https://python-mss.readthedocs.io/en/latest/examples.html#opencv-numpy) to record the screen.
But the frames are getting delayed with time(exponentially), I think there are lots of GC happening.
I interrupted the command line after `fps: 0.07140145917730202` because the display window was not responding.
Ways to reproduce: It is happening every time.

### Full message

 ```
Rohits-MacBook-Pro:drive rohitarya$ python3 readscreen.py 
fps: 4.144634697781783
fps: 1.2977357482958785
fps: 0.3543577094166482
fps: 0.07140145917730202
^Cpython3(19339,0x7fffe9aae3c0) malloc: *** mach_vm_map(size=8404176896) failed (error code=4)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
python3(19339,0x7fffe9aae3c0) malloc: *** mach_vm_map(size=8404176896) failed (error code=4)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
python3(19339,0x7fffe9aae3c0) malloc: *** mach_vm_map(size=8404176896) failed (error code=4)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
python3(19339,0x7fffe9aae3c0) malloc: *** mach_vm_map(size=8404176896) failed (error code=4)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
python3(19339,0x7fffe9aae3c0) malloc: *** mach_vm_map(size=8404176896) failed (error code=4)
*** error: can't allocate region
```

### Other Information
Rest of the examples(Part of the screen, PIL, Playing with pixels) are working perfectly fine.

**Comment by BoboTiG** [comment]
Hello,

Do you are trying the exact same code as in the example?
I will give a shot this weekend, thanks for the report :)

**Comment by aryarohit07** [comment]
Thanks for a prompt reply.
Yes, I tried the exact same code as in the example.

I tried to debug more and here are some more insights:
when the loop starts, the first `img = numpy.array(sct.grab(monitor))` captures the specified rect from the whole screen (as expected).
Now the second iteration captures the same rect but **from the cv2 window** `cv2.imshow('img', img)`. So the second iteration is nested window of previous one.
The third iteration captures from the second window.
And the loop goes on.

Here is a screenshot after three iterations.
<img width="1277" alt="screen shot 2017-07-13 at 1 15 55 pm" src="https://user-images.githubusercontent.com/4436955/28155763-b31993b8-67cd-11e7-90e6-af78edab625f.png">

Hope this helps.

**Comment by arpit-kalla** [comment]
Getting the same error. I printed out the size of the numpy array "img"  and it seems to increase exponentially for some reason. (I have changed fps to seconds to frame)

<img width="1265" alt="screen shot 2017-07-13 at 5 14 50 pm" src="https://user-images.githubusercontent.com/30146812/28164863-f9d9e048-67ee-11e7-9773-44e213c95818.png">

**Comment by arpit-kalla** [comment]
Kindof solved the issue by putting the `monitor = {'top': 40, 'left': 0, 'width': 100, 'height': 100}
` line inside the loop. Dont know why this exactly works but I assume the monitor values are getting updated by mistake in the grab function

**Comment by BoboTiG** [comment]
Thank you for the investigation :)
It seems that you are right, somewhat modifes `monitors` inplace. I will check that!

**Comment by BoboTiG** [comment]
Hello, could you try with the latest version in the dev branch please?
I removed the border effect with monitor's width.
