### ISSUE TITLE
GetSystemMetrics module returns wrong screen resolution after running sct.grab(monitor)

### ISSUE THREAD

**Issue by anonymousvic** [BoboTiG/python-mss#197]
General information:

* OS name: _Windows 10_
* OS version: __20H2__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _2560x1600_(Scale is 175% and the resolution after it is 1463x914)

* Python version: _3.8.5_
* MSS version: __6.1.0__

### Description of the warning/error

Neither

### Full message

    Nope

### Other details

First python code is below:
```python
from win32.win32api import GetSystemMetrics
w = GetSystemMetrics (0)
h = GetSystemMetrics (1)
```

It can return the right resolution: 1463x914

Second python code is below:
```python
from win32.win32api import GetSystemMetrics
import mss

left, top, right, bottom = (100,100,900,700)
with mss.mss() as sct:
    # Part of the screen to capture
   monitor = {'top': top, 'left': left, 'width': right-left, 'height': bottom-top}
   world_sct = np.array(sct.grab(monitor))

w = GetSystemMetrics (0)
h = GetSystemMetrics (1)
```
It returns: 2560x1600

GetSystemMetrics gives the wrong resolution after taking a screen shot by mss

**Comment by BoboTiG** [comment]
`GetSystemMetrics` is for Windows, not GNU/Linux.

Also, please fill the issue template, I cannot help without information.

**Comment by BoboTiG** [comment]
Also, the latest release is 6.1.0. 3.1.2 is quite old.

**Comment by anonymousvic** [comment]
> Also, the latest release is 6.1.0. 3.2.0 is quite old.

Sorry, I pressed the "enter" with incaution when I was filling the template, and I'm filling it now.

**Comment by BoboTiG** [comment]
What is the resolution set on the monitor? 2560x1600 seems appropriate with 175% scale. 🤔

**Comment by anonymousvic** [comment]
> What is the resolution set on the monitor? 2560x1600 seems appropriate with 175% scale. 🤔

My screen size is 13 inches and the resolution is 2560x1600, so I set 175% scale to make everything bigger

**Comment by narumishi** [comment]
`mss` instance will set High DPI awareness = PROCESS_PER_MONITOR_DPI_AWARE. So before using mss, the **PROCESS** is NOT DPI aware, you got 1463x914. Once mss instance created, the **PROCESS** is DPI aware, then you got the actual resolution 2560x1600.

What's more, during the full lifecycle of **PROCESS**, DPI awareness can be only set once programmatically or in manifest. Although Windows10 introduces Mixed-Mode DP-aware and support **THREAD** DPI awareness?

For more details: https://docs.microsoft.com/en-us/windows/win32/hidpi/setting-the-default-dpi-awareness-for-a-process

**Comment by BoboTiG** [comment]
Thanks @narumishi :)
@anonymousvic this is not a bug indeed.
