### ISSUE TITLE
Save compress time, so i sugguest decrease default compression_level to 1

### ISSUE THREAD

**Issue by Wanyor** [BoboTiG/python-mss#199]
First, thank you very much for writing a very very useful library.

Then, i have some sugguests:

General information:

* OS name: _Windows_
* OS version: __10.0.19041.685__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _1366x768_
    * Monitor 2: _1920x1080_
* Python version: Python 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)] on win32
* MSS version: __6.1.0__

### Description of the warning/error

I want to reduce every grab time, so i decrease default compression_level to 1(zlib compress level), it works,haha

### Full message
Small is better

    level 1:
![image](https://user-images.githubusercontent.com/3807732/103875600-99b2f900-510d-11eb-8298-d7db74642e30.png)

level default(6):
![image](https://user-images.githubusercontent.com/3807732/103875785-ccf58800-510d-11eb-9a91-9f2f2119b0e7.png)

### Other details

Share to somebody who was in need.

**Comment by BoboTiG** [comment]
I needed to pick a default value good for the speed and the file size. I found that 6 is a good start, it is also the default value in the `zlib` module.

You can easily change the value in your script and from the command line.

**Comment by Wanyor** [comment]
OK, thanks for your reply. Maybe screencapture was not good at RAT tool，haha.

**Comment by BoboTiG** [comment]
Another way would be to use something else than PNG for the output file. Some format with a better compression / speed ration. But this is up to you to implement that :)
