### ISSUE TITLE
A high-DPI display isn't detected correctly in Windows 10

### ISSUE THREAD

**Issue by andrei-shabanski** [BoboTiG/python-mss#20]
General informations:

* OS name: Windows 10
* OS version: 10.0.15063
* OS architecture: 64 bits
* Result of the `platform.uname()`: uname_result(system='Windows', node='DESKTOP-GTK56RF', release='10', version='10.0.15063', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
* Result of the command `python --version`: Python 3.6.1 (MSC v.1900 32 bit (Intel)0)

### Description of the warning/error

A high-DPI display isn't detected correctly in Windows 10.

### Full message

Windows 10 allows scaling UI elements. My pc has the scaling size 125% and the resolution 1920x1080. But mmscan't detect the monitor with these settings correctly:

```python
>>> from mss import mss
>>> sct = mss()
>>> sct.monitors
[{'height': 864, 'left': 0, 'top': 0, 'width': 1536},
 {'height': 864, 'left': 0, 'top': 0, 'width': 1536}]
```

When I change the scaling size to 100%, mms works fine.

**Comment by BoboTiG** [comment]
Hello,

Thank you for the report.
Could you post a screen shot please? I am curious to see what is the result.

I have no W10 now, but I will try whenever I can.

**Comment by andrei-shabanski** [comment]
These are results of `sct.shot()` and `sct.grab({'height': 1080, 'left': 0, 'top': 0, 'width': 1920}`
https://cl.ly/lZOg
https://cl.ly/lZXs

**Comment by BoboTiG** [comment]
Thanks.
I could reproduce the issue. Will try to find a workaround soon.

**Comment by BoboTiG** [comment]
Hello,
Could you try the latest version from the `dev` branhc please?

**Comment by andrei-shabanski** [comment]
It looks good! https://cl.ly/lz5L

**Comment by fraeraser** [comment]
Hello
I've just tested last mss version from `dev`
On W10, with an upscaled UI at 125%, everything is fine, but if I set 150% or more, the bottom and right sides are still cropped :(

**Comment by BoboTiG** [comment]
Hello @fraeraser, could you open a new issue please?
