### ISSUE TITLE
Example code seems to be wrong

### ISSUE THREAD

**Issue by daftshady** [BoboTiG/python-mss#21]
https://python-mss.readthedocs.io/en/dev/examples.html#playing-with-pixels

In this example, `sct.monitor` is passed directly to `grab` method.
In osx, `grab` changes a value of `monitor` param. As a result of it, the value of `sct.monitor` is also changed because python passes reference of `dict` rather than copying it.
(https://github.com/BoboTiG/python-mss/blob/master/mss/darwin.py#L182)

I think it's better to copy the dict before passing it to `grab`.
```
sct_img = sct.grab(sct.monitors[1].copy())
```

**Comment by BoboTiG** [comment]
Hello,

Thank for the report, I will change the behavior in `darwin.py`. I thought it was the solution to adapt `monitor` inside `grab()` method, but it seems it is not (related to #19).

I will have a look soon.

**Comment by BoboTiG** [comment]
Hello, could you try with the latest version in the dev branch please?
I removed the border effect with monitor's width.

**Comment by Kanter666** [comment]
Hi, I've been trying to use this library on macbook for a week but without success. It might be related to this issue. When I try to do multiple screenshots they get smaller every time and then I get an error: `fps: 10.603887304572943 fps: 6.476309296242654 fps: 1.5442678274713213 fps: 0.3302173072344628 fps: 0.07009281260164726 Python(88098,0x7ffff3c513c0) malloc: *** mach_vm_map(size=16808349696) failed (error code=4) *** error: can't allocate region *** set a breakpoint in malloc_error_break to debug Python(88098,0x7ffff3c513c0) malloc: *** mach_vm_map(size=16808349696) failed (error code=4) *** error: can't allocate region` .  When I tried it with develop branch I got directly this error without any screenshots `File "/usr/local/lib/python3.6/site-packages/mss-3.1.0-py3.6.egg/mss/base.py", line 124, in shot
  File "/usr/local/lib/python3.6/site-packages/mss-3.1.0-py3.6.egg/mss/base.py", line 113, in save
  File "/usr/local/lib/python3.6/site-packages/mss-3.1.0-py3.6.egg/mss/darwin.py", line 183, in grab
mss.exception.ScreenShotError: ('Data length mismatch.', {'buf_len': 20736000, 'data_ref': 4663480320, 'prov': 140635299539760, 'image_ref': 140635299599408, 'rect': <mss.darwin.CGRect object at 0x115799a60>, 'rounded_width': 1440, 'monitor': {'left': 0, 'top': 0, 'width': 1440, 'height': 900}, 'self': <mss.darwin.MSS object at 0x10ed881d0>})
`
Ps.: I tried every example and it always failed, if I have some time I will try to look into it

**Comment by BoboTiG** [comment]
Could you open a new issue with the last error you get please?

**Comment by BoboTiG** [comment]
@Kanter666: Retry with the latest dev branch. It should be OK.
