### ISSUE TITLE
Xvfb error while trying to open multiple xvfb screens in single python session

### ISSUE THREAD

**Issue by mudassirkhan19** [BoboTiG/python-mss#210]
General information:

* OS name: Ubuntu
* OS version: 20.04
* OS architecture: 64 bits
* Resolutions:
    * Monitor 1: 1920x1080
* Python version: 3.8.10
* MSS version: 6.1.0

For GNU/Linux users:

* Display server protocol and version, if known: Xorg
* Desktop Environment: Gnome
* Composite Window Manager name and version: Not sure

### Description of the warning/error

The error comes when I try to call mss.mss() in a single python session with two different Xvfb screens.

### Full message

`XIO:  fatal IO error 0 (Success) on X server ":3"
      after 8 requests (8 known processed) with 0 events remaining.`

### Other details

Steps to reproduce:

``` python
from xvfbwrapper import Xvfb
import mss
import os

xvfb = Xvfb(width=1920, height=1080, colordepth=24)
xvfb.start()

with mss.mss() as sct:
    pass
xvfb.stop()

xvfb = Xvfb(width=1920, height=1080, colordepth=24)
xvfb.start()

with mss.mss() as sct:
    pass
```
The error pops up exactly [on this line](https://github.com/BoboTiG/python-mss/blob/78e5a8de625734ae84235a82af03a803d56da58b/mss/linux.py#L323)

**Comment by BoboTiG** [comment]
Could you try to reset that attribute before the second use of MSS?

```python
from mss.liux import MSS

# (...)
xvfb.stop()

MSS._display_dict.clear()

xvfb = Xvfb(width=1920, height=1080, colordepth=24)
# (...)
```

**Comment by mudassirkhan19** [comment]
thanks @BoboTiG !
I have been trying to battle this bug for two days.

**Comment by BoboTiG** [comment]
Great!
I could introduce a `mss.reset_internal_state()` to hide implementation details. Or maybe shorter: `mss.reset()`.
With a good documentation it should help with such situation.

**Comment by mudassirkhan19** [comment]
Shouldn't the context manager take care of this?
this can just happen behind the scenes, just a thought.

**Comment by BoboTiG** [comment]
Actually those internal details were added for performance reasons.
Your situation is not so frequent, so I would go with the new function to clear the internal state.

**Comment by mudassirkhan19** [comment]
Encountered another issue with this, this time its a too many open files error, the issue comes here:
`self.xlib.XOpenDisplay(disp)`
So basically we aren't closing our connection to the X11 server, a little digging led me to an `XCloseDisplay` function from [here](https://linux.die.net/man/3/xopendisplay).
So wrote a wrapper for my usecase:
``` python
from contextlib import contextmanager
import sys

@contextmanager
def mss_wrapper():
    try:
        with mss.mss() as sct:
            yield sct
    finally:
        if sys.platform == "linux":
            from mss.linux import MSS
            import ctypes

            x11 = ctypes.util.find_library("X11")  # type: ignore
            xlib = ctypes.cdll.LoadLibrary(x11)
            for _, display in MSS._display_dict.items():
                xlib.XCloseDisplay(display)
            MSS._display_dict.clear()
```

**Comment by dp-alvarez** [comment]
I've run into the same issue as @mudassirkhan19 (thanks for the wrapper by the way!).

I feel like it makes a lot of sense for the display to get closed and the dict cleared on the context exit, in which case would someone avoid this?

Also, out of curiosity, why share the display among all MSS instances in a thread instead of each MSS instance having it's own?
Right now one can only use MSS to connect to one display per thread, clearing the dict solves this partially but you can't have two MSS instances connected to different displays in the same thread.
X apparently doesn't mind multiple connections to the same display per thread since I'm using other libraries each with their own display.

**Comment by BoboTiG** [comment]
@dp-alvarez
> Also, out of curiosity, why share the display among all MSS instances in a thread instead of each MSS instance having it's own?

At first, it was to workaround resource leaks. But I now see that it's not a good way, and there may be no way to handle all cases. So I refactored the whole part in #234, and it should be better for most of us.
