### ISSUE TITLE
Pytest --strict option is deprecated

### ISSUE THREAD

**Issue by CTPaHHuK-HEbA** [BoboTiG/python-mss#213]
Run pytest

====== warnings summary =============================================================================================== C:\Program Files\Python310\lib\site-packages\_pytest\config\__init__.py:1198                                                                                                                                      C:\Program Files\Python310\lib\site-packages\_pytest\config\__init__.py:1198: PytestRemovedIn8Warning: The --strict option is deprecated, use --strict-markers instead.  

Need
```
--- a/setup.cfg
+++ b/setup.cfg
@@ -51,7 +51,7 @@ max-line-length = 120
 [tool:pytest]
 addopts =
     --showlocals
-    --strict
+    --strict-markers
```

**Comment by BoboTiG** [comment]
Would you mind opening a PR?

I definitely need to update the CI to use GitHub workflows. Will try to do it in a decent delay.
