### ISSUE TITLE
Example PIL

### ISSUE THREAD

**Issue by CTPaHHuK-HEbA** [BoboTiG/python-mss#22]
[https://python-mss.readthedocs.io/en/dev/examples.html#pil](https://python-mss.readthedocs.io/en/dev/examples.html#pil)
Os Windows

1.
```
        # Create the Image, solution 1 (slower)
        # img = Image.frombytes('RGB', sct_img.size, sct_img.content)
```
sct_img.content - no attribute into sct_img

2. 
```
        # Create the Image, solution 2
        img = Image.frombytes('RGBA', sct_img.size, bytes(sct_img.raw), 'raw', 'BGRA')
        img = img.convert('RGB')  # Convert to RGB
```
Equivalent, which is faster
`    img = Image.frombytes('RGB', sct_img.size, sct_img.rgb, 'raw')`

**Comment by BoboTiG** [comment]
Hello,

Thank you for the report, it is fixed with the commit 9fe7a1fe429f7ada151fd5443729a5c479ce5b65.

**Comment by CTPaHHuK-HEbA** [comment]
after fix doc:

```
        # Create the Image, solution 1 (slower)
        # img = Image.frombytes('RGB', sct_img.size, sct_img.rgb)

        # Create the Image, solution 2
        img = Image.frombytes('RGB', sct_img.size, sct_img.rgb, 'raw')
```

Maby del 1 exampl or 2 and del world "slower" - speed is equivalent

**Comment by BoboTiG** [comment]
You are right :)
Done in e6cc1ebcbb834316cba75602743bed8140ceb1a3.
