### ISSUE TITLE
Screenshots have poor color accuracy 

### ISSUE THREAD

**Issue by wkaisertexas** [BoboTiG/python-mss#221]
General information:

* OS name: MacOS
* OS version: 13.0.1 
* OS architecture: ARM
* Resolutions:
    * Monitor 1: 2560 x 1664
* Python version: 3.9.15
* MSS version: 7.0.1

### Description of the warning/error

Colors get washed out when taking monitor captures

### Full message

Running the numpy / opencv sample code from the documentation and noticed that the color gets extremely washed out. The macbook I am running this on has a 10-bit panel. Perhaps some of this information could be getting lost, but I am not quite sure. 

<img width="965" alt="Screenshot 2022-12-30 at 6 23 17 PM" src="https://user-images.githubusercontent.com/27795014/210119630-8a133c8b-2383-4d20-9419-0fad553c6590.png">

### Code Used
```python
import cv2
import numpy

import mss
import time
with mss.mss() as sct:
    # Part of the screen to capture
    monitor = {"top": 40, "left": 0, "width": 800, "height": 640}

    while "Screen capturing":
        last_time = time.time()

        # Get raw pixels from the screen, save it to a Numpy array
        img = numpy.array(sct.grab(monitor))

        # Display the picture
        cv2.imshow("OpenCV/Numpy normal", img)

        # Display the picture in grayscale
        # cv2.imshow('OpenCV/Numpy grayscale',
        #            cv2.cvtColor(img, cv2.COLOR_BGRA2GRAY))

        print(f"fps: {1 / (time.time() - last_time)}")

        # Press "q" to quit
        if cv2.waitKey(25) & 0xFF == ord("q"):
            cv2.destroyAllWindows()
            break
```

**Comment by BoboTiG** [comment]
When you save to a PNG file using `sct.shot()`, do you see the color issue too?

**Comment by wkaisertexas** [comment]
Yes, the colors are also faded there. It is just far more noticeable with the hall of mirrors effect created by taking multiple screenshots

**Comment by BoboTiG** [comment]
I should get a Mac soon, until then I can't do anything.

**Comment by wkaisertexas** [comment]
Looking back, I think it is an HDR 10 bit versus SDR 8 bit issue. Somehow, the color space is getting converted, so when converting back the colors do not look quite right.

I found something similar with Adobe photoshop and screenshots getting washed out.

[https://community.adobe.com/t5/photoshop-ecosystem-discussions/screenshot-has-faded-colors-when-pasted-into-photoshop/td-p/11757932](https://community.adobe.com/t5/photoshop-ecosystem-discussions/screenshot-has-faded-colors-when-pasted-into-photoshop/td-p/11757932)

Might be worth taking a look at.

**Comment by laerson-hammes** [comment]
This happens because you use OpenCV, you need to convert the image color before showing it on the screen
````
cv2.cvtColor(np.array(pyautogui.screenshot()), cv2.COLOR_RGB2BGR)
````

**Comment by wkaisertexas** [comment]
<img width="820" alt="Screenshot 2023-10-26 at 8 00 05 PM" src="https://github.com/BoboTiG/python-mss/assets/27795014/76300934-8793-4f67-976b-6136f8a63579">

That is definitely not the issue. It is an issue with the P3 Color Space being converted down to Standard Dynamic Range (SDR) which causes colors to become compressed.
