### ISSUE TITLE
Running OpenCV/Numpy example makes window larger and larger until crash

### ISSUE THREAD

**Issue by McMaNGOS** [BoboTiG/python-mss#26]
General informations:

* OS name: _macOS_
* OS version: __10.12.5__
* OS architecture: _64 bits_
* Result of the command `python --version`: __Python 2.7.10__

### Description of the warning/error

When running [this code](https://python-mss.readthedocs.io/en/dev/examples.html#opencv-numpy), the output window will gradually increase in size until the program crashes.

### Full message

```
(cv) Guests-MBP:opencv admin$ python scratch.py
sh: sysctl: command not found
fps: 14.7629580092
fps: 49.8900215294
fps: 36.1858683461
fps: 12.818855861
fps: 2.33973450345
fps: 0.709336639047
fps: 0.214847465514
Traceback (most recent call last):
  File "scratch.py", line 16, in <module>
    img = numpy.array(sct.grab(monitor))
  File "/Users/admin/.virtualenvs/cv/lib/python2.7/site-packages/mss/darwin.py", line 168, in grab
    'CoreGraphics.CGWindowListCreateImage() failed.', locals())
mss.exception.ScreenShotError: ('CoreGraphics.CGWindowListCreateImage() failed.', {'self': <mss.darwin.MSS object at 0x10aa80e10>, 'image_ref': None, 'monitor': {'width': 12288, 'top': 40, 'height': 12800, 'left': 40}, 'rect': <mss.darwin.CGRect object at 0x10aa834d0>, 'rounded_width': 12288.0})
```

### Other details

A (rather large) GIF of the issue:

![56cb8a2d30e92267df9406a65db1c7a8](https://user-images.githubusercontent.com/671341/29525482-1bc2b816-8693-11e7-9fcf-d1304ee928a8.gif)

**Comment by BoboTiG** [comment]
Hello,

It is the same bug as reported in #19. It is fixed in the `dev` branch and will be merged into master soon. Thank you for the report.
