### ISSUE TITLE
How to exclude mouse cursor from screenshot?

### ISSUE THREAD

**Issue by kkew3** [BoboTiG/python-mss#260]
General information:

* OS name: _macOS Monterey_
* OS version: __12.6.5 (21G531)__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _2880 × 1800_
    * Monitor 2: _1920 × 1080_
* Python version: _3.9.7_
* MSS version: __9.0.1__

For GNU/Linux users:

* Display server protocol and version, if known: __X server__
* Desktop Environment: _XFCE 4_
* Composite Window Manager name and version: __Cairo v1.14.6__

### Description of the warning/error

The screenshot includes a mouse cursor even if `with_cursor=False`.

```python
import pyautogui
import mss
with mss.mss(with_cursor=False) as sct:
    pyautogui.moveTo(100, 100)
    pyautogui.click()
    sct.shot(output='x.png')
```

Open `x.png` and there will be a mouse cursor at coordinate (100, 100).

### Full message

No warning or error message.

**Comment by BoboTiG** [comment]
I just tried a simple script with only MSS, and no cursor is included. BTW the cursor is not included by default, you have to specifically ask for it using `with_cursor=True`.

**Comment by kkew3** [comment]
On my computer, without using `pyautogui`, if I invoke the script via keyboard, once I type on the keyboard, e.g. typing "python ...", the mouse cursor disappears automatically, thus not included in `mss`'s screenshot. Therefore, the use of `pyautogui` to force the appearance of mouse cursor is a must to reproduce the error.

**Comment by BoboTiG** [comment]
Oh, sorry I read too quickly the description.

Currently `with_cursor` is only implemented on GNU/Linux. It seems that pyautogui is painting the cursor rather than moving it? And so it is part of the low-level image that MSS captures (simplified).
Anyway, as MSS on macOS doen't know yet how to include the cursor, the issue should be raised on the pyautogui repository I guess.

**Comment by BoboTiG** [comment]
To see the cursor when you want to test, add a `time.sleep(5)` before `mss.shot()` so that you have time to move the cursor.

**Comment by kkew3** [comment]
Thank you so much for your reply. I've found a workaround, which is to press Esc key, again using `pyautogui`, immediately before invoking `mss`, and the cursor is not included. Should I close the issue?

**Comment by shininome** [comment]
```python 
   def get_now_screen(self):
        monitor = {"top": 0, "left": 0, "width": 1075, "height": 900}
        with mss.mss() as sct:
            while True:
                pyautogui.press('esc',2,interval=0.1) 
                now_screen = np.array(sct.grab(monitor))
                # Put the captured screen in the queue
                self.queue.put(now_screen)
```
How did you solve the problem? I tried pressing 'Esc,' but it didn't work. The mouse pointer also appeared in the screenshot

**Comment by kkew3** [comment]
My use case can be seen [here](https://github.com/kkew3/sat-minesweeper/blob/master/vboard.py#L85), where I coded `pyautogui.press('esc')` only.
