### ISSUE TITLE
$display not set

### ISSUE THREAD

**Issue by WanMMao** [BoboTiG/python-mss#265]
General information:

* OS name: _Debian GNU/Linux_
* OS version: __sid__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _1920x1080_
* Python version: _3.8.0
* MSS version: 9.0.1

info:
 I will start the Python script in rc. local 
this code is as follows：
<img width="663" alt="image" src="https://github.com/BoboTiG/python-mss/assets/28594366/70ea4f7a-d746-42ac-a3eb-bdc5e8ea2ee8">

error info is $display not set
May I ask what the reason is

Please help me check what the reason is

**Comment by BoboTiG** [comment]
It seems similar to #263 but with `rc.local`. I do not have the exact answer, but you should be able to find in on internet.
I will be happy to know the answer too :)

**Comment by WanMMao** [comment]
> rc.local

If I don't start in rc.local, the code is normal, and this issue only occurs when I start in rc.local. I am confused

**Comment by WanMMao** [comment]
os.environ['DISPLAY']=':0'
  os.environ['Xauthority']='/home/username/.Xauthority'

use the code

I solved the problem
