### ISSUE TITLE
Content of mss().monitors does not correspond with screen resolution, cannot take screenshots

### ISSUE THREAD

**Issue by edelmanjm** [BoboTiG/python-mss#30]
General informations:

* OS name: _macOS_
* OS version: _10.13.1 "High Sierra"_
* OS architecture: _64 bits_
* Monitor(s)'s resolution: 2880x1800, default system scaling/resolution
* Result of the command `python --version`: __Python 2.7.10__, however `python3 --version` yields __Python 3.6.2__ (which is what was used.)

### Description of the warning/error

The content of `mss().monitors` is incorrect:
```
from mss import mss
mss().monitors
```
returns `[{'left': 0, 'top': 0, 'width': 1680, 'height': 1050}, {'left': 0, 'top': 0, 'width': 1680, 'height': 1050}]`

### Full message

    N/A

### Other details

So far this is the only computer I've tested this on that has this issue, and it's the only hi-DPI computer I own.

**Comment by karanlyons** [comment]
This isn’t a bug if you take those bounds to be in screen coordinates as opposed to pixel coordinates, which is technically the correct way to handle things in macOS.

**Comment by edelmanjm** [comment]
@karanlyons Except for the fact that taking screenshots at all is broken on high DPI displays because the wrong size is reported. If that's the correct way of doing things on macOS, then something else is handling things wrong.

**Comment by karanlyons** [comment]
That’s actually a separate issue (though it is related to the same misunderstanding), but I’ve fixed it in https://github.com/BoboTiG/python-mss/pull/32 which should be accepted soon (I’ve one more commit to make first).

**Comment by edelmanjm** [comment]
@karanlyons Guess this should just be titled differently then. @BoboTiG asked me to open another issue when this was being discussed on #24.

**Comment by karanlyons** [comment]
Yeah, the short version is that up until you actually generate an image of pixels you want to do all your work in coordinate space. A “retina” display has a 4:1 pixel:point ratio, so 1440x900 is the correct set of bounds to report from `monitors`. If we tried to manage things in pixel space farther up we’d run into issues with MacOS’s display APIs, and rightly so as dealing with screen coordinates makes everything far easier.

**Comment by edelmanjm** [comment]
@karanlyons I changed the issue to reflect the nature of the problem, so it should remain open. Also, 1440x900 seems incorrect; 1680x1050 seems correct, as that's what my Mac reports as the coordinates when using the built-in screenshot utility (press <kbd>Command</kbd>+<kbd>Shift</kbd>+<kbd>4</kbd> to see this.)

**Comment by karanlyons** [comment]
My retina display at the “stock” configuration (4:1) reports 1440x900 as the screen bounds, which is matches by mss. If I change the resolution to 1680x1050 in System Preferences the bounds are reported as 1680x1050 by your Grab test, *and* by mss (at least after my patch):

```python
>>> from mss import mss; mss().monitors
[{'left': 0, 'top': 0, 'width': 1680, 'height': 1050}, {'left': 0, 'top': 0, 'width': 1680, 'height': 1050}]
```

Are you using mss from HEAD, and can you confirm this behavior?

**Comment by edelmanjm** [comment]
@karanlyons Default on my display is "looks like 1680x1050." Changing this is reflected in mss. Which computer are you using?

**Comment by karanlyons** [comment]
That’s an odd default for the MBP (not sure the default was ever anything other than “Best for Display” which is 1440x900), but the good news is that if that resolution is reflected in mss then there’s no lingering issue here. Your screen is 1680x1050 _points_ which are being displayed on a 2880x1800 _pixel_ monitor, so `monitors` should show 1680x1050, and a screenshot should be 2880x1800 pixels.

**Comment by edelmanjm** [comment]
@karanlyons Yup, seems good. Not sure why that'd be an odd default though. Which computer are using using?

**Comment by karanlyons** [comment]
MacBook Pro (Retina, 15-inch, Late 2013).

It’s an odd default because as it isn’t an integer multiple of 2280x1800 your output to your physical display will be fuzzy. But that doesn’t affect mss at all.

**Comment by edelmanjm** [comment]
@karanlyons ¯\_(ツ)_/¯ Not fuzzy at all, it scales perfectly and is the default.

**Comment by karanlyons** [comment]
Ah, interesting, it appears on some releases (either of the hardware or the OS, not sure which) the default was changed: https://9to5mac.com/2016/12/02/15-inch-macbook-pro-screen-resolution-blurry/

 Anyway, that’s out of scope for the bug report here. I think this can be closed.

**Comment by edelmanjm** [comment]
@karanlyons Whatever trickery they're doing it's awfully good. I think this should remain open until a fix that makes it possible to *actually take screenshots* without crashing (the main purpose of this library) should remain open. I'm happy to edit the issue as appropriate, but this is a bug, and does need to be fixed.

**Comment by karanlyons** [comment]
Does the latest version (installed from the repository, with my now accepted PR) still crash for you?

**Comment by edelmanjm** [comment]
@karanlyons Yes, didn't realize your branch had been merged in.
