### ISSUE TITLE
Unreasonable memory usage on OS X

### ISSUE THREAD

**Issue by zmcgohan** [BoboTiG/python-mss#31]
General informations:

* OS name: _Debian GNU/Linux_
* OS version: __sid__
* OS architecture: _64 bits_
* Monitor(s)'s resolution: 
* Result of the command `python --version`: __Python 3.5.1+__

For GNU/Linux users:

* Display server protocol and version, if known: __X server__
* Desktop Environment: _XFCE 4_
* Composite Window Manager name and version: __Cairo v1.14.6__

### Description of the warning/error

Using mss (master branch or dev, both were tested) to take screenshots over any length of time on Mac results in a huge memory footprint and eventually the OS force-closing the program for exceeding the max usage.

### Other details

Even at around 400 screenshots taken, my memory used is over 4 GB. This happens whether I instantiate mss() for each screenshot or re-use the same mss() object for all screenshots.

Can be reproduced by using the second OpenCV/NumPy example without the imshow()s and a longer runtime of 10+ seconds (at which point it's at the aforementioned 4 GB memory usage).

**Comment by BoboTiG** [comment]
Hello,

Thanks for the report. I just tried with the master branch and all went fine.
I fixed memory leaks reported in #24 and it should be OK now.

Doing as you said (removing `imgshow()` and longer runtime) I got 937 screenshots using MSS and the memory did not go higher than 51 Mo.
Could you retry with the updated master branch?
