### ISSUE TITLE
'MSS' object has no attribute 'get_pixels'

### ISSUE THREAD

**Issue by TurtleForGaming** [BoboTiG/python-mss#41]
General informations:

* OS name: Windows
* OS version: 10
* OS architecture: 32 bits
* Monitor(s)'s resolution: ?? (Two monitor)
* Result of the command `python --version`: Python 2.7.14

### Description of the warning/error
Full code:
```

import numpy as np
import cv2
from mss import mss
from PIL import Image

mon = {'top': 160, 'left': 160, 'width': 200, 'height': 200}

sct = mss()

while 1:
    sct.get_pixels(mon)
    img = Image.frombytes('RGB', (sct.width, sct.height), sct.image)
    cv2.imshow('test', np.array(img))
    if cv2.waitKey(25) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        break
```

### Full message

```
Traceback (most recent call last):
  File "C:\Users\Samuel\Desktop\scr2.py", line 11, in <module>
    sct.get_pixels(mon)
AttributeError: 'MSS' object has no attribute 'get_pixels'

c:\Users\Samuel\Desktop>
```

**Comment by BoboTiG** [comment]
Hello,

You code is not right, check those examples:
- [OpenCV/Numpy](https://python-mss.readthedocs.io/examples.html#opencv-numpy)
- [PIL](https://python-mss.readthedocs.io/examples.html#pil)

The 1st one demonstrate quite well what you want to achevie.

**Comment by TurtleForGaming** [comment]
thk i was looking into that
