### ISSUE TITLE
Possible to save frames from videos with a high FPS?

### ISSUE THREAD

**Issue by tejaskhot** [BoboTiG/python-mss#45]
```
from time import time
import mss
import mss.tools

start = time()
count = 1

while True:
	with mss.mss() as sct:
	    # The screen part to capture
	    monitor = {'top': 144, 'left': 80, 'width': 1397, 'height': 782}
	    output = 'frames/sct-{}.png'.format(count)
	    count += 1
	    # Grab the data
	    sct_img = sct.grab(monitor)

	    # Save to the picture file
	    mss.tools.to_png(sct_img.rgb, sct_img.size, output)
	    # print(output)
	    now = time()
	    if (now - start) % 60 >= 10: break
```
This seems to save only around 100 frames for 10 seconds. Can this be improved?

**Comment by BoboTiG** [comment]
Hello,

2 things are slowing down the process:

1. `sct_img.rgb` which is a on demand attribute. It means that its value is computed only when required, and computed one time only.
2. `mss.tools.to_png(sct_img.rgb, sct_img.size, output)` which creates the whole PNG structure. If we omit the `output` argument, nothing is written to the file but instead the PNG raw bytes are returned (new in version 3.1.2). But it makes no differences.

I benchmarked on my OS (I am using SSD):

    # Just grabbing
    926

    # Grabbing + accessing `sct_img.rgb`
    660

    # Grabbing + to_png(output=None)
    251

    # Grabbing + to_png(output=output)
    249

As you can see, there are 2 rooms of improvement: [Screenshot.rgb](https://github.com/BoboTiG/python-mss/blob/fe69e5d8d99adce453422cb122c4ca848fd1c76e/mss/screenshot.py#L138-L140) and [to_png()](https://github.com/BoboTiG/python-mss/blob/fe69e5d8d99adce453422cb122c4ca848fd1c76e/mss/tools.py#L11). If you have better implementations, pure Python only, I am open to suggestions and patches :)

**Comment by BoboTiG** [comment]
Another thing in your benchmark, you can save a lot by not creating a new `MSS` instance each time:

    from time import time
    import mss
    import mss.tools

    start = time()
    count = 0

    # The screen part to capture
    monitor = {'top': 144, 'left': 80, 'width': 1397, 'height': 782}

    with mss.mss() as sct:
        while True:
            output = 'frames/sct-{}.png'.format(count)
            count += 1

            # Grab the data
            sct_img = sct.grab(monitor)

            # Save to the picture file
            mss.tools.to_png(sct_img.rgb, sct_img.size, output)
            # print(output)
            now = time()
            if (now - start) % 60 >= 10: break

**Comment by BoboTiG** [comment]
Little improvement in the branch https://github.com/BoboTiG/python-mss/tree/improvements, but it concerns only the `Screenshot` instanciation. A first win, but nothing interesting regarding that issue :)

**Comment by FrancescoCeruti** [comment]
It's possible to add a decent improvement in `to_png` by changing the [zlib.compress](https://docs.python.org/3/library/zlib.html#zlib.compress) level at `idat = [b'', b'IDAT', zlib.compress(scanlines), b'']` [here](https://github.com/BoboTiG/python-mss/blob/d0b838ee7ab2b2bd301a9446e692356cdd6e5892/mss/tools.py#L38).

Doing some tests it can get x3 time faster without any compression, and x2 time with the minimum level, if the first case the file is a lot bigger (in my case 3M vs 200K).

Here the tests results, to give a general idea on the impact *(on a 6 years old linux laptop, non-ssd)*:

**Current -1 (default level, 6, according to the docs)**

    Total time: 0.039415 s
    Line #      Hits         Time  Per Hit   % Time  Line Contents

    27                                           @do_profile
    28                                           def to_png(data, size, output=None):
    29                                               # type: (bytes, Tuple[int, int], Optional[str]) -> Union[None, bytes]
    30                                               """
    31                                               Dump data to a PNG file.  If `output` is `None`, create no file but return
    32                                               the whole PNG data.
    33                                           
    34                                               :param bytes data: RGBRGB...RGB data.
    35                                               :param tuple size: The (width, height) pair.
    36                                               :param str output: Output file name.
    37                                               """
    38                                           
    39         1            4      4.0      0.0      width, height = size
    40         1            2      2.0      0.0      line = width * 3
    41         1            7      7.0      0.0      png_filter = struct.pack('>B', 0)
    42         1         2206   2206.0      5.6      scanlines = b''.join([png_filter + data[y * line:y * line + line] for y in range(height)])
    43                                           
    44         1           20     20.0      0.1      magic = struct.pack('>8B', 137, 80, 78, 71, 13, 10, 26, 10)
    45                                           
    46                                               # Header: size, marker, data, CRC32
    47         1            4      4.0      0.0      ihdr = [b'', b'IHDR', b'', b'']
    48         1            6      6.0      0.0      ihdr[2] = struct.pack('>2I5B', width, height, 8, 2, 0, 0, 0)
    49         1           24     24.0      0.1      ihdr[3] = struct.pack('>I', zlib.crc32(b''.join(ihdr[1:3])) & 0xffffffff)
    50         1            3      3.0      0.0      ihdr[0] = struct.pack('>I', len(ihdr[2]))
    51                                           
    52                                               # Data: size, marker, data, CRC32
    53         1        36592  36592.0     92.8      idat = [b'', b'IDAT', zlib.compress(scanlines), b'']
    54         1          145    145.0      0.4      idat[3] = struct.pack('>I', zlib.crc32(b''.join(idat[1:3])) & 0xffffffff)
    55         1            8      8.0      0.0      idat[0] = struct.pack('>I', len(idat[2]))
    56                                           
    57                                               # Footer: size, marker, None, CRC32
    58         1            2      2.0      0.0      iend = [b'', b'IEND', b'', b'']
    59         1            2      2.0      0.0      iend[3] = struct.pack('>I', zlib.crc32(iend[1]) & 0xffffffff)
    60         1            2      2.0      0.0      iend[0] = struct.pack('>I', len(iend[2]))
    61                                           
    62         1            1      1.0      0.0      if not output:
    63                                                   # Returns raw bytes of the whole PNG data
    64                                                   return magic + b''.join(ihdr + idat + iend)
    65                                           
    66         1          135    135.0      0.3      with open(output, 'wb') as fileh:
    67         1            6      6.0      0.0          fileh.write(magic)
    68         1            4      4.0      0.0          fileh.write(b''.join(ihdr))
    69         1          133    133.0      0.3          fileh.write(b''.join(idat))
    70         1          107    107.0      0.3          fileh.write(b''.join(iend))
    71                                           
    72         1            2      2.0      0.0      return None

**Using 1 (minimum)**

    Total time: 0.018258 s

    Line #      Hits         Time  Per Hit   % Time  Line Contents

    27                                           @do_profile
    28                                           def to_png(data, size, output=None):
    29                                               # type: (bytes, Tuple[int, int], Optional[str]) -> Union[None, bytes]
    30                                               """
    31                                               Dump data to a PNG file.  If `output` is `None`, create no file but return
    32                                               the whole PNG data.
    33                                           
    34                                               :param bytes data: RGBRGB...RGB data.
    35                                               :param tuple size: The (width, height) pair.
    36                                               :param str output: Output file name.
    37                                               """
    38                                           
    39         1            4      4.0      0.0      width, height = size
    40         1            3      3.0      0.0      line = width * 3
    41         1            8      8.0      0.0      png_filter = struct.pack('>B', 0)
    42         1         2529   2529.0     13.9      scanlines = b''.join([png_filter + data[y * line:y * line + line] for y in range(height)])
    43                                           
    44         1           17     17.0      0.1      magic = struct.pack('>8B', 137, 80, 78, 71, 13, 10, 26, 10)
    45                                           
    46                                               # Header: size, marker, data, CRC32
    47         1            4      4.0      0.0      ihdr = [b'', b'IHDR', b'', b'']
    48         1            6      6.0      0.0      ihdr[2] = struct.pack('>2I5B', width, height, 8, 2, 0, 0, 0)
    49         1           18     18.0      0.1      ihdr[3] = struct.pack('>I', zlib.crc32(b''.join(ihdr[1:3])) & 0xffffffff)
    50         1            2      2.0      0.0      ihdr[0] = struct.pack('>I', len(ihdr[2]))
    51                                           
    52                                               # Data: size, marker, data, CRC32
    53         1        15047  15047.0     82.4      idat = [b'', b'IDAT', zlib.compress(scanlines, 1), b'']
    54         1          187    187.0      1.0      idat[3] = struct.pack('>I', zlib.crc32(b''.join(idat[1:3])) & 0xffffffff)
    55         1            9      9.0      0.0      idat[0] = struct.pack('>I', len(idat[2]))
    56                                           
    57                                               # Footer: size, marker, None, CRC32
    58         1            1      1.0      0.0      iend = [b'', b'IEND', b'', b'']
    59         1            2      2.0      0.0      iend[3] = struct.pack('>I', zlib.crc32(iend[1]) & 0xffffffff)
    60         1            2      2.0      0.0      iend[0] = struct.pack('>I', len(iend[2]))
    61                                           
    62         1            1      1.0      0.0      if not output:
    63                                                   # Returns raw bytes of the whole PNG data
    64                                                   return magic + b''.join(ihdr + idat + iend)
    65                                           
    66         1          132    132.0      0.7      with open(output, 'wb') as fileh:
    67         1            6      6.0      0.0          fileh.write(magic)
    68         1            5      5.0      0.0          fileh.write(b''.join(ihdr))
    69         1          168    168.0      0.9          fileh.write(b''.join(idat))
    70         1          105    105.0      0.6          fileh.write(b''.join(iend))
    71                                           
    72         1            2      2.0      0.0      return None

**Using 0 (no compression)**

    Total time: 0.012227 s

    Line #      Hits         Time  Per Hit   % Time  Line Contents

    27                                           @do_profile
    28                                           def to_png(data, size, output=None):
    29                                               # type: (bytes, Tuple[int, int], Optional[str]) -> Union[None, bytes]
    30                                               """
    31                                               Dump data to a PNG file.  If `output` is `None`, create no file but return
    32                                               the whole PNG data.
    33                                           
    34                                               :param bytes data: RGBRGB...RGB data.
    35                                               :param tuple size: The (width, height) pair.
    36                                               :param str output: Output file name.
    37                                               """
    38                                           
    39         1            4      4.0      0.0      width, height = size
    40         1            3      3.0      0.0      line = width * 3
    41         1            8      8.0      0.1      png_filter = struct.pack('>B', 0)
    42         1         2250   2250.0     18.4      scanlines = b''.join([png_filter + data[y * line:y * line + line] for y in range(height)])
    43                                           
    44         1           18     18.0      0.1      magic = struct.pack('>8B', 137, 80, 78, 71, 13, 10, 26, 10)
    45                                           
    46                                               # Header: size, marker, data, CRC32
    47         1            4      4.0      0.0      ihdr = [b'', b'IHDR', b'', b'']
    48         1            5      5.0      0.0      ihdr[2] = struct.pack('>2I5B', width, height, 8, 2, 0, 0, 0)
    49         1           19     19.0      0.2      ihdr[3] = struct.pack('>I', zlib.crc32(b''.join(ihdr[1:3])) & 0xffffffff)
    50         1            3      3.0      0.0      ihdr[0] = struct.pack('>I', len(ihdr[2]))
    51                                           
    52                                               # Data: size, marker, data, CRC32
    53         1         2843   2843.0     23.3      idat = [b'', b'IDAT', zlib.compress(scanlines, 0), b'']
    54         1         3884   3884.0     31.8      idat[3] = struct.pack('>I', zlib.crc32(b''.join(idat[1:3])) & 0xffffffff)
    55         1           11     11.0      0.1      idat[0] = struct.pack('>I', len(idat[2]))
    56                                           
    57                                               # Footer: size, marker, None, CRC32
    58         1            2      2.0      0.0      iend = [b'', b'IEND', b'', b'']
    59         1            4      4.0      0.0      iend[3] = struct.pack('>I', zlib.crc32(iend[1]) & 0xffffffff)
    60         1            2      2.0      0.0      iend[0] = struct.pack('>I', len(iend[2]))
    61                                           
    62         1            2      2.0      0.0      if not output:
    63                                                   # Returns raw bytes of the whole PNG data
    64                                                   return magic + b''.join(ihdr + idat + iend)
    65                                           
    66         1          140    140.0      1.1      with open(output, 'wb') as fileh:
    67         1            4      4.0      0.0          fileh.write(magic)
    68         1            4      4.0      0.0          fileh.write(b''.join(ihdr))
    69         1         2558   2558.0     20.9          fileh.write(b''.join(idat))
    70         1          457    457.0      3.7          fileh.write(b''.join(iend))
    71                                           
    72         1            2      2.0      0.0      return None

**Comment by BoboTiG** [comment]
We can add a `level=6` argument to `to_png()`. That argument will be set via a `MSS.compress_level`. What do you think?

**Comment by FrancescoCeruti** [comment]
Perfect, that would allow users to choose the compression level depending on their needs. I'd suggest to use `compression_level` or `compression` which seems a more self-explaining name.

I may also suggest to @tejaskhot that a multiprocessing solution will likely improve performance, depending on the hardware.

Something like this:

    from os import makedirs
    from time import time
    from multiprocessing import Pool, cpu_count

    import mss
    from mss.tools import to_png

    makedirs('frames', exist_ok=True)

    with mss.mss() as sct:
        monitor = sct.monitors[0]

        with Pool(processes=cpu_count()//2) as pool:
            start = time()
            now = start
            count = 0
        
            while (now - start) % 60 < 10:
                output = 'frames/sct-{}.png'.format(count)
                count += 1
                
                # Grab the data
                sct_img = sct.grab(monitor)

                # Save to the picture file
                # >> EXECUTED IN A DIFFERENT PROCESS <<
                pool.apply_async(to_png, (sct_img.rgb, sct_img.size, output))

                now = time()

            pool.close()
            pool.join()

**Comment by BoboTiG** [comment]
OK, added the option in the "impvements" branch.

**Comment by BoboTiG** [comment]
So, now you have full control on PNG compression level (merged in master). It is all good for you @tejaskhot or do you need other improvements?

**Comment by eruffaldi** [comment]
I have reached 37 FPS on macOS by two changes:
- introduce a Grabber object with specified monitor size that allocates OS resources once. Edited for both darwin.py and windows
- use BGRA encoding because RGB one in class Snapshot perform for loop over points. BGRA is not fully supported by pillow but then it can be loaded in pillow and converted to RGB using pillow function. Other uses as numpy or OpenCV are fine

Pull Request in preparation

**Comment by eruffaldi** [comment]
Just forgot:
 Image.frombytes('RGBX', sct_img.size, sct_img.bgra)

**Comment by BoboTiG** [comment]
I just pushed some improvements on the master branch. I think it is the max we can do for now (tweaking the compression level + code optimizations). For comparison, I benchmarked:

```
GNU/Linux    Original Patched   Gain %
  grab           2618    2738    +4.58
  access_rgb     1083    1128    +4.15
  output          324     322   ------
  save            320     319   ------

macOS
  grab            524     526   ------
  access_rgb      396     406    +2.52
  output          194     195   ------
  save            193     194   ------

Windows
  grab           1280    2498   +95.16
  access_rgb      574     712   +24.04
  output          139     188   +35.25
  save            138     186   +34.78
```

Numbers are the count of captured screenshots in 10 seconds. You can find the test file in `tests/benchmarks.py`. I did not bench the compression level, but you can easily acheive 400+ screenshots with a level of `2`.

It is not possible to tweak macOS grabbing, your best bet is to change the compression level and/or use @FrancescoCeruti code, which is quite smart.

I will push changes to PiPy the next week, I will first let you try the code and let me know your thoughts.
