### ISSUE TITLE
Content of mss().monitors does not correspond with secondary screen resolution, cannot take screenshots (Windows 8.1)

### ISSUE THREAD

**Issue by pnprog** [BoboTiG/python-mss#49]
General informations:

* OS name: __Windows__
* OS version: __8.1__
* OS architecture: __64 bits__
* Monitor(s)'s resolution: __Monitor 1: 1600x900 ; Monitor 2: 1920x1080__
* Result of the command `python --version`: __Python 2.7.9__

### Description of the warning/error

The content of mss().monitors is incorrect:

```
import mss
for monitor in mss.mss().monitors:
	print monitor
```

Return: 
```
{'width': 2880, 'top': 0, 'height': 900, 'scale': 1.0, 'left': 0}
{'width': 1600, 'top': 0, 'height': 900, 'scale': 1.0, 'left': 0}
{'width': 1280, 'top': 0, 'height': 720, 'scale': 1.0, 'left': 1600}
```
The third line does not correspond with the secondary monitor resolution.

### Full message
Here is a testing script I made:
```
import mss
import mss.tools
from Tkinter import *
app = Tk()

def screenshot():
	top = btn.winfo_rooty()
	left = btn.winfo_rootx()
	width = btn.winfo_width()
	height = btn.winfo_height()
	
	selection = {'top': top, 'left': left, 'width': width, 'height': height}
	sct_img = mss.mss().grab(selection)
	mss.tools.to_png(sct_img.rgb, sct_img.size, output="screenshot.png")


btn=Button(app, text="Grab a screenshot", command=screenshot)
btn.pack(fill=X,padx=50, pady=50)

print "Monitors:"
for monitor in mss.mss().monitors:
	print monitor

app.mainloop()
```
The script creates a simple Tkinter windows with a buton. A click on the buton save a screenshot of that button, using the coordinate provided by Tkinter.

This works when the windows is on the primary monitor, but does not work after I drag the windows on the secondaty monitor: the screenshot represents another part of the monitor.

### Other details

When I set the secondary monitor resolution to correspond with the resolution provided by mss, then the screenshot works perfectly on both monitors.

The script works just fine on Ubuntu.

**Comment by BoboTiG** [comment]
Hello,

The thing is that MSS will not use the content of `monitors` but the values you sent, such as values returned by `btn.winfo_*()`.  Could you print the content of `selection`?

**Comment by pnprog** [comment]
Hello,
Thanks for your quick answer!

So I modifed the function as below:

```
def screenshot():
	top = btn.winfo_rooty()
	left = btn.winfo_rootx()
	width = btn.winfo_width()
	height = btn.winfo_height()
	
	selection = {'top': top, 'left': left, 'width': width, 'height': height}
	print selection
	sct_img = mss.mss().grab(selection)
	print sct_img
	mss.tools.to_png(sct_img.rgb, sct_img.size, output="screenshot.png")
```

Then, when on monitor 1, I get:
```
{'width': 105, 'top': 185, 'height': 26, 'left': 162}
<ScreenShot pos=162,185 size=105x26>
```
And on monitor 2, I get:
```
{'width': 105, 'top': 254, 'height': 26, 'left': 1862}
<ScreenShot pos=1862,254 size=105x26>
```

Is there  something I am doing wrong?

**Comment by BoboTiG** [comment]
If I get it right, you are passing the Tk button size and position to MSS, not the monitor information.
Instead of `btn.winfo_*()`, try, if possible, to use `app.winfo_*()`.

Because as of now, MSS is working right: you give him some dimensions and he does. The informations are not the one you are waiting for. For instance, `selection` should have the same size as your monitors, but it is not the case.

Also, to be clear: MSS does not use `monitors` when you direct call `grab()`, it will uses the data you will give him (here it is the content of `selection`).

**Comment by pnprog** [comment]
> If I get it right, you are passing the Tk button size and position to MSS, not the monitor information.
> Instead of btn.winfo_*(), try, if possible, to use app.winfo_*().

Yes, you are right!

I am sorry, I haven't been clear from the beginning. In fact, I don't try to take a screenshot of the whole secondary monitor, but only a screenshot of part of the screen. In my application, this is a Tkinter canvas, but to demonstrate this issue, I made a simple script that take a screenshot of the button widget.

So normally, by passing the Tk button size and position to MSS, I should get a screenshot of that button:

![screenshot](https://user-images.githubusercontent.com/25114663/35204998-f43eca02-ff6c-11e7-8e4a-4822ab84d885.png)

I and get that correct screenshot when the Tk application is on the primary monitor, but not when it is on the secondary monitor, if I run the app on Windows 8.1
On the secondary monitor, I get a screenshot of another part of the desktop.

But I get the proper result when running this test on Ubuntu, with the same computer and same monitors, both on primary and secondary monitors.

I also noticed two things:

* The second screen resolution, as reported by `mss.mss().monitors` is correct on Ubuntu, but not on Windows 8.1
* When, on Windows 8.1, I manually set the second screen resolution to match the resolution reported by `mss.mss().monitors`, then the script works well and I get the proper screenshot

The above two points made me conclude that this issue is related to a wrongly detected resolution of the second monitor. But maybe I went too fast to that conclusion and maybe both issues are in fact unrelated?

If both issues are unrelated:

* Could it mean that the information reported by Tk (`winfo_rootx()` and `winfo_rooty()`) are wrong?
* Do you want to rename this issue? and maybe open another issue for the wrong screen resolution as reported by `mss.mss().monitors` on Windows 8.1?

Thanks for your help!

**Comment by BoboTiG** [comment]
It will be hard for me to reproduce, I have no W8.1. The code that guesses monitors information is [here](https://github.com/BoboTiG/python-mss/blob/beb43aed25382a28ca6884554ac81f2e6c401f9c/mss/windows.py#L114-L134), it seems legit but perhaps could you find something wrong here.

**Comment by pnprog** [comment]
Hi!
It maybe also an issue with my specific installation of Windows 8.1 (maybe the drivers or something else). This is not for a critical feature, so I pushed the code "in production" anyway. I will let you know if I get similar feedback.
