### ISSUE TITLE
Add a shortcut to take automatically use the proper MSS class

### ISSUE THREAD

**Issue by sametmax** [BoboTiG/python-mss#5]
Something like: 

```
from platform import system

def mss(*args, **kwargs):
    """ Factory returning a proper MSS class instance 

        It detects the plateform we are running on 
        and choose the most adapted mss_class to take
        screenshots.
        
        It then proxies its arguments to the class for 
        instanciation.
    """

    mss_class = {
        'Darwin': MSSMac,
        'Linux': MSSLinux,
        'Windows': MSSWindows
    }[system()]

    return mss_class(*args, **kwargs)
```

So so mss can be used as simply as: 

````
from mss import mss

screenshotter = mss()
for f in screenshotter.save():
    print(f)

```

This avoid to write the same boiler plate over and over fow the most common use case.

**Comment by BoboTiG** [comment]
Yes, it is a good idea. Should I do like that to alert the user his system is not implemented ?

    try:
        mss_class = {
            'Darwin': MSSMac,
            'Linux': MSSLinux,
            'Windows': MSSWindows
        }[system()]
    except KeyError:
        err = 'MSS: system "{0}" not implemented.'.format(system())
        raise ScreenshotError(err)

    return mss_class(*args, **kwargs)

`ScreenshotError` ou `NotImplementedError` ?
