### ISSUE TITLE
Hi-DPI not correctly detected in Windows 10

### ISSUE THREAD

**Issue by ryanfox** [BoboTiG/python-mss#57]
General informations:

* OS name: _Windows_
* OS version: __10, version 1709__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _3840x2160_
    * Monitor 2: _3840x2160_
* Python version: _3.6.1_
* MSS version: __3.2.0__

### Description of the warning/error

I have two monitors, both 3840x2160. My scaling is 200%. Screenshotting either one individually, or both together crops the right and bottom sides. I get two 2880x1620 images, or one 5760x1620.

`monitors` returns these values:

    >>> for m in sct.monitors:
        print(m)
    
    {'left': 0, 'top': 0, 'width': 5760, 'height': 1620, 'scale': 1.5}
    {'left': 0, 'top': 0, 'width': 2880, 'height': 1620, 'scale': 1.5}
    {'left': 2880, 'top': 0, 'width': 2880, 'height': 1620, 'scale': 1.5}

### Other details

Dividing the resolution by 1.5 and multiplying by 2 gives the correct resolution - it seems to just be detecting the scaling incorrectly. I think this is related to #20.

**Comment by ryanfox** [comment]
If I manually specify the resolution, it captures the full desktop across both monitors:

    sct.grab({'left': 0, 'top': 0, 'width': 7680, 'height': 2160, 'scale': 2})

lets me save the full image.

**Comment by ryanfox** [comment]
I found a workaround - you need to make Python DPI-aware:

    import ctypes
    ctypes.windll.user32.SetProcessDPIAware(1)

Executing that before creating the `sct` object gives me full-resolution screenshots of both monitors.

**Comment by BoboTiG** [comment]
Hello,

Thank you for the report and the fix!
Do you are interested in opening a PR?
If not, I will try to fix it in the day :)

**Comment by ryanfox** [comment]
I haven't thoroughly tested it - it's just a fix for my use case :) If you're ok with applying the change for everyone, I am happy to make a PR.
