### ISSUE TITLE
[XServer] Library makes program hard crash when monitor is out of bounds

### ISSUE THREAD

**Issue by RedFantom** [BoboTiG/python-mss#61]
General information:

* OS name: _Ubuntu (`ubuntu-desktop`)_
* OS version: __18.04 LTS__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _1920x1080 (laptop built-in)_
    * Monitor 2: _1366x768 (external)_
* Python version: _3.6.5_
* MSS version: __3.2.0__

For GNU/Linux users:

* Display server protocol and version, if known: __X server__ _(X.Org version: 1.19.6)_
* Desktop Environment: _Gnome 3_
* Composite Window Manager name and version: __???__ (The default one, I guess?)

### Description of the warning/error
This error occurs when the a monitor that is out of bounds is specified in the `grab()` call.
```python
from mss import mss

screenshotter = mss()
monitor = {
    "left": -30,
    "top": 0,
    "width": 100,
    "height": 100,
}
try:
    screenshotter.grab(monitor)  # X Error
except BaseException as e:
    # Never reached
    print("Handling error")
```
Using a monitor like `{"left": 0, "top": 0, "width": 10000, "height": 100}` has the same result.
### Full message
```stderr
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  73 (X_GetImage)
  Serial number of failed request:  91
  Current serial number in output stream:  91
```
The message is printed to `stderr`, then the Python interpreter quits with exit code `1`.

### Other details
I discovered this because I let my program generate a box based on the location of the cursor. Then I take the screenshot of only the cursor area.

While it might be better for efficiency not to check the bounds of the monitor, I personally don't think causing this type of hard crash is acceptable. It's up to you. If you decide not to check bounds, I think a mention of this in the documentation would be appropriate.

**Comment by BoboTiG** [comment]
Thank you for the report.

You are totally right that this kind of crash is not acceptable. It will be fixed in the next release: the error will raise a specific exception instead of crashing the interpreter.
