### ISSUE TITLE
libpng warning on linux

### ISSUE THREAD

**Issue by capaximperii** [BoboTiG/python-mss#7]
I have been using mss as the engine behind gui automation for linux in conjunction with visgrep and on some systems i get the following error.
    libpng warning: Ignoring bad adaptive filter type
Then on systems with composite window managers, there is a bug as documented here:
    https://bugs.launchpad.net/unity-2d/+bug/1081674

Is there a way to be able to capture the screen *as i see it*, without it rasterizing transparent layers that X windows seems to be introducing into the screenshot that is messing with the pattern matching.

**Comment by BoboTiG** [comment]
Thank you for the report capaximperii, I will check ASAP :)

**Comment by BoboTiG** [comment]
I pushed an update to pip to solve the "bad adaptative filter". It seems to resolve the issue.

Could you open a second issue for the other problem (with all informations needed as the OS version, Python version and whatever you think good)?

**Comment by capaximperii** [comment]
Thank you, i have merged it with AutomationFramework Command line. I will try to gather more information as the fix trickles down to people that use it. I really appreciate this library and how well it fits with my linux automation testing effort.

**Comment by capaximperii** [comment]
One of the problem systems with a custom built Linux-Gnome OS, now works fine with the fix.
