### ISSUE TITLE
Getting ZPIXMAX error in version 4.0.0

### ISSUE THREAD

**Issue by klausrollmann** [BoboTiG/python-mss#92]
General informations:

* OS name: _Debian GNU/Linux_
* OS version: __sid__
* OS architecture: _64 bits_
* Resolutions:
    * Monitor 1: _1280x900_
* Python version: _3.5.3_
* MSS version: __4.0.0__

For GNU/Linux users:

* Display server protocol and version, if known: __X server__
* Desktop Environment: _Gnome__

### Description of the warning/error

After upgrading to version 4.0.0 I started getting error ZIPXMAP in grab.

### Full message
```python
  File "/home/user/image.py", line 149, in refresh
    im = np.asarray(sct.grab(monitor))
  File "/home/user/.local/lib/python3.5/site-packages/mss/linux.py", line 389, in grab
    ZPIXMAP,
ctypes.ArgumentError: argument 3: <class 'TypeError'>: wrong type
```
### Other details

Downgrading to version 3.3.2 solved the problem.

**Comment by BoboTiG** [comment]
Thanks for the report! And sorry for the regression, tests were passing locally and on the CI :/

I will push the fix very soon and release the 4.1.0 version.

**Comment by BoboTiG** [comment]
Coul you test from the master branch and confirm it is fixed?

**Comment by BoboTiG** [comment]
Great! I will make a new release today then ;)
